'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { apiRequest } from '../../../lib/api';

type Staff = { id: string; staffId?: string; firstName?: string; lastName?: string; position?: string };
const money = (v: unknown) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(Number(v) || 0);

export default function StaffWalletWithdrawalPage() {
  const [staff, setStaff] = useState<Staff[]>([]); const [staffId, setStaffId] = useState(''); const [amount, setAmount] = useState(''); const [reference, setReference] = useState(''); const [description, setDescription] = useState('Daily field cash settlement'); const [result, setResult] = useState<any>(null); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { apiRequest('/staff').then((d:any) => setStaff(Array.isArray(d) ? d : Array.isArray(d?.data) ? d.data : [])).catch((e:any) => setError(e?.message || 'Unable to load staff.')); }, []);
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(''); setResult(null); try { if (!staffId || Number(amount) <= 0) throw new Error('Select staff and enter a valid amount.'); const data = await apiRequest('/staff-wallet/settle', { method: 'POST', body: JSON.stringify({ staffId, amount: Number(amount), reference: reference || undefined, description }) }); setResult(data); setAmount(''); setReference(''); } catch (e:any) { setError(e?.message || 'Unable to settle staff cash.'); } finally { setSaving(false); } }
  return <main className="min-h-screen bg-slate-50 p-5 text-slate-800 md:p-8"><div className="mx-auto max-w-3xl"><header className="mb-6 rounded-3xl bg-gradient-to-r from-emerald-800 to-orange-500 p-6 text-white"><p className="text-xs font-black tracking-widest text-orange-100">PWFB STAFF DAILY WALLET</p><h1 className="text-3xl font-black">Settle Field Cash</h1><p className="mt-1 text-sm text-emerald-50">Return accountable cash and reduce the selected staff wallet balance.</p><Link href="/staff-daily-wallet" className="mt-4 inline-block rounded-xl bg-white/15 px-4 py-2 text-sm font-bold">← Staff Daily Wallet</Link></header>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{result&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">Settlement posted. New wallet balance: {money(result.newBalance)}</div>}<form onSubmit={submit} className="grid gap-4 rounded-3xl bg-white p-6 shadow-sm"><label className="grid gap-2 text-sm font-bold">Staff<select className="rounded-xl border p-3" value={staffId} onChange={e=>setStaffId(e.target.value)} required><option value="">Select staff</option>{staff.map(s=><option key={s.id} value={s.id}>{s.firstName} {s.lastName} — {s.position||'Staff'}{s.staffId?` · ${s.staffId}`:''}</option>)}</select></label><label className="grid gap-2 text-sm font-bold">Settlement amount (₦)<input className="rounded-xl border p-3" type="number" min="0" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="grid gap-2 text-sm font-bold">Reference<input className="rounded-xl border p-3" value={reference} onChange={e=>setReference(e.target.value)} placeholder="Settlement reference"/></label><label className="grid gap-2 text-sm font-bold">Description<input className="rounded-xl border p-3" value={description} onChange={e=>setDescription(e.target.value)}/></label><button disabled={saving} className="rounded-xl bg-emerald-700 p-3 font-black text-white">{saving?'Posting…':'Settle Staff Cash'}</button></form></div></main>;
}
