services:
  - type: web
    name: pwfb-backend
    runtime: node
    plan: starter
    rootDir: .
    buildCommand: npm ci && npm run build:backend
    startCommand: npm run start:prod --workspace=backend
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: pwfb-frontend
    runtime: node
    plan: starter
    rootDir: .
    buildCommand: npm ci && npm run build:frontend
    startCommand: npm run start --workspace=pwfb-frontend
    autoDeploy: true
