'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api';

type Staff={id:string;firstName?:string;lastName?:string;employeeId?:string}; type Period={id:string;name:string;status:string}; type Item={id:string;staffId:string;basicSalary:number;allowances:number;deductions:number;netSalary:number;staff?:Staff}; type Payroll={id:string;status:string;totalBasic:number;totalAllowances:number;totalDeductions:number;totalNet:number;period?:Period;branch?:{name:string};items?:Item[]}; type Account={balance:number;currency:string;account:string};
const money=(v:number)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v)||0);
export default function PayrollPage(){
 const[payrolls,setPayrolls]=useState<Payroll[]>([]),[periods,setPeriods]=useState<Period[]>([]),[selected,setSelected]=useState<Payroll|null>(null),[periodId,setPeriodId]=useState(''),[account,setAccount]=useState<Account|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){setLoading(true);setError('');try{const[rows,ps,b]=await Promise.all([apiRequest('/payroll'),apiRequest('/periods'),apiRequest('/payroll/head-office-balance')]);setPayrolls(Array.isArray(rows)?rows:[]);setPeriods(Array.isArray(ps)?ps:[]);setAccount(b||null);const open=(Array.isArray(ps)?ps:[]).find((p:Period)=>p.status==='OPEN');setPeriodId(c=>c||open?.id||'')}catch(e:any){setError(e.message||'Unable to load payroll.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function createPayroll(){if(!periodId)return setError('Select an open financial period first.');setBusy(true);setError('');try{await apiRequest('/payroll',{method:'POST',body:JSON.stringify({periodId})});await load()}catch(e:any){setError(e.message||'Unable to create payroll.')}finally{setBusy(false)}}
 async function refresh(id:string){const fresh=await apiRequest(`/payroll/${id}`);setSelected(fresh);setPayrolls(rows=>rows.map(r=>r.id===id?fresh:r))}
 async function saveItem(id:string,item:Item){setBusy(true);setError('');try{await apiRequest(`/payroll/${id}/items`,{method:'POST',body:JSON.stringify({staffId:item.staffId,basicSalary:Number(item.basicSalary)||0,allowances:Number(item.allowances)||0,deductions:Number(item.deductions)||0})});await refresh(id)}catch(e:any){setError(e.message||'Unable to save payroll item.')}finally{setBusy(false)}}
 async function action(id:string,endpoint:string){setBusy(true);setError('');try{await apiRequest(`/payroll/${id}/${endpoint}`,{method:'PATCH'});await load();if(selected?.id===id)await refresh(id)}catch(e:any){setError(e.message||'Payroll action failed.')}finally{setBusy(false)}}
 return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">HUMAN RESOURCES & FINANCE</p><h1 className="pwfb-page-title">Payroll</h1><p className="pwfb-page-description">Prepare salaries, approve payroll and pay staff from the Head Office Account.</p></div><Link href="/dashboard" className="pwfb-secondary-button">← Dashboard</Link></div>{error&&<div className="pwfb-alert">{error}</div>}
 <section className="account-card"><div><span>HEAD OFFICE ACCOUNT</span><h2>{loading?'—':money(account?.balance||0)}</h2><p>Available balance for salary payments</p></div><b>NGN</b></section>
 <section className="pwfb-panel payroll-create"><div><p className="pwfb-eyebrow">NEW PAYROLL RUN</p><h2>Create from an open financial period</h2><p>Active staff are added automatically and salary values can be entered before approval.</p></div><div className="controls"><select value={periodId} onChange={e=>setPeriodId(e.target.value)}><option value="">Select open period</option>{periods.filter(p=>p.status==='OPEN').map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button className="pwfb-primary-button" disabled={busy||!periodId} onClick={createPayroll}>{busy?'Working…':'+ Create Payroll Run'}</button></div></section>
 <section className="pwfb-stat-grid"><div className="pwfb-stat-card"><span>Payroll Runs</span><strong>{loading?'—':payrolls.length}</strong><small>All payroll records</small></div><div className="pwfb-stat-card pwfb-stat-orange"><span>Total Net Payroll</span><strong>{loading?'—':money(payrolls.reduce((s,p)=>s+Number(p.totalNet||0),0))}</strong><small>Across visible runs</small></div><div className="pwfb-stat-card"><span>Head Office Balance</span><strong>{loading?'—':money(account?.balance||0)}</strong><small>Salary funding available</small></div></section>
 <section className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Payroll Register</h2><p>Draft, approved and paid payroll runs.</p></div><span className="pwfb-record-count">{payrolls.length} records</span></div><div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Period</th><th>Branch</th><th>Staff</th><th>Net</th><th>Status</th><th>Actions</th></tr></thead><tbody>{payrolls.map(p=><tr key={p.id}><td><strong>{p.period?.name||'—'}</strong></td><td>{p.branch?.name||'All branches'}</td><td>{p.items?.length||0}</td><td>{money(p.totalNet)}</td><td><span className="pwfb-status-badge">{p.status}</span></td><td><button className="pwfb-secondary-button" onClick={()=>setSelected(p)}>Open</button>{p.status==='DRAFT'&&<button className="pwfb-secondary-button" disabled={busy} onClick={()=>action(p.id,'approve')}>Approve</button>}{p.status==='APPROVED'&&<button className="pay-button" disabled={busy||(account?.balance||0)<p.totalNet} onClick={()=>action(p.id,'pay')}>Pay Salary</button>}</td></tr>)}{!loading&&!payrolls.length&&<tr><td colSpan={6}>No payroll records found. Create the first run from an open financial period.</td></tr>}</tbody></table></div></section>
 {selected&&<section className="pwfb-panel payroll-editor"><div className="pwfb-panel-header"><div><p className="pwfb-eyebrow">PAYROLL DETAILS</p><h2>{selected.period?.name||'Payroll run'}</h2><p>{selected.status} • {selected.items?.length||0} staff records</p></div><button className="pwfb-secondary-button" onClick={()=>setSelected(null)}>Close</button></div>{selected.status!=='DRAFT'&&<div className="pwfb-alert">This payroll is {selected.status.toLowerCase()} and can no longer be edited.</div>}<div className="payroll-items">{(selected.items||[]).map(item=><PayrollItemEditor key={item.id} item={item} disabled={selected.status!=='DRAFT'||busy} onSave={()=>saveItem(selected.id,item)}/>)}</div><div className="payroll-total">Total net: <strong>{money(selected.totalNet)}</strong></div>{selected.status==='APPROVED'&&<div className="pay-confirm"><div><strong>Pay staff from Head Office Account</strong><span>{money(selected.totalNet)} will be deducted immediately.</span></div><button className="pay-button" disabled={busy||(account?.balance||0)<selected.totalNet} onClick={()=>action(selected.id,'pay')}>{busy?'Processing…':'Pay Salary'}</button></div>}</section>}
 <style jsx>{`.account-card{display:flex;justify-content:space-between;align-items:center;padding:22px 24px;margin-bottom:18px;border-radius:18px;background:linear-gradient(135deg,#075b2b,#168043);color:#fff}.account-card span{font-size:10px;letter-spacing:.14em;font-weight:900;color:#c9ead4}.account-card h2{margin:5px 0;font-size:30px}.account-card p{margin:0;color:#d9eee0;font-size:12px}.account-card b{padding:10px 13px;border-radius:10px;background:#f28c18}.payroll-create{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:18px}.payroll-create h2{margin:4px 0;font-size:19px}.payroll-create p:not(.pwfb-eyebrow){margin:0;color:#718078;font-size:12px}.controls{display:flex;gap:10px;align-items:center}.controls select{min-width:220px;padding:11px;border:1px solid var(--pwfb-border);border-radius:10px;background:#fff}.pwfb-primary-button,.pay-button{border:0;border-radius:10px;padding:11px 15px;background:var(--pwfb-green);color:#fff;font-weight:800;cursor:pointer}.pay-button{background:#f28c18}.pwfb-primary-button:disabled,.pay-button:disabled{opacity:.5;cursor:not-allowed}.payroll-editor{margin-top:18px}.payroll-items{display:grid;gap:10px}.payroll-item{display:grid;grid-template-columns:1.5fr repeat(3,1fr) auto;gap:10px;align-items:end;padding:13px;border:1px solid var(--pwfb-border);border-radius:12px}.payroll-item label{display:block;color:#718078;font-size:10px;font-weight:700}.payroll-item input{width:100%;box-sizing:border-box;padding:9px;border:1px solid var(--pwfb-border);border-radius:8px;margin-top:4px}.payroll-staff strong,.payroll-staff small{display:block}.payroll-staff strong{font-size:12px}.payroll-staff small{color:#7a867f;font-size:10px}.payroll-total{display:flex;justify-content:flex-end;gap:8px;margin-top:16px;padding-top:14px;border-top:1px solid var(--pwfb-border)}.pay-confirm{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:18px;padding:14px;border-radius:12px;background:#fff8ed;border:1px solid #f5d4a5}.pay-confirm strong,.pay-confirm span{display:block}.pay-confirm strong{font-size:12px}.pay-confirm span{margin-top:3px;color:#806f5a;font-size:11px}@media(max-width:800px){.payroll-create{display:block}.controls{margin-top:14px;flex-direction:column;align-items:stretch}.controls select{min-width:0}.payroll-item{grid-template-columns:1fr 1fr}.payroll-staff{grid-column:1/-1}.payroll-item button{grid-column:1/-1}.pay-confirm{align-items:stretch;flex-direction:column}}`}</style></main>;
}
function PayrollItemEditor({item,disabled,onSave}:{item:Item;disabled:boolean;onSave:()=>void}){const[value,setValue]=useState(item);const name=`${value.staff?.firstName||'Staff'} ${value.staff?.lastName||''}`.trim();return <div className="payroll-item"><div className="payroll-staff"><strong>{name}</strong><small>{value.staff?.employeeId||value.staffId}</small></div><label>Basic<input type="number" min="0" value={value.basicSalary} disabled={disabled} onChange={e=>setValue({...value,basicSalary:Number(e.target.value)})}/></label><label>Allowances<input type="number" min="0" value={value.allowances} disabled={disabled} onChange={e=>setValue({...value,allowances:Number(e.target.value)})}/></label><label>Deductions<input type="number" min="0" value={value.deductions} disabled={disabled} onChange={e=>setValue({...value,deductions:Number(e.target.value)})}/></label><button className="pwfb-secondary-button" disabled={disabled} onClick={onSave}>Save</button></div>}
