export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  LOAN_OFFICER = 'LOAN_OFFICER',
  TELLER = 'TELLER',
  AUDITOR = 'AUDITOR',
  CUSTOMER = 'CUSTOMER',
}
