"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { apiRequest } from "../../lib/api";

type Row = Record<string, any>;
type Data = { customers: Row[]; staff: Row[]; loans: Row[]; savings: Row[]; deposits: Row[]; withdrawals: Row[]; transfers: Row[] };
const empty: Data = { customers: [], staff: [], loans: [], savings: [], deposits: [], withdrawals: [], transfers: [] };
const labels: Record<keyof Data, string> = { customers: "Customers", staff: "Staff", loans: "Loans", savings: "Savings", deposits: "Daily Deposits", withdrawals: "Daily Withdrawals", transfers: "Transfers" };
const icons: Record<keyof Data, string> = { customers: "👥", staff: "◉", loans: "▣", savings: "₦", deposits: "↓", withdrawals: "↑", transfers: "↔" };
const operationLinks: Record<keyof Data, string> = { customers: "/customers", staff: "/staff", loans: "/loans", savings: "/savings", deposits: "/banking?operation=deposit", withdrawals: "/banking?operation=withdraw", transfers: "/banking?operation=transfer" };
function money(v: any) { return `₦${Number(v || 0).toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function name(x: Row) { return [x.firstName, x.middleName, x.lastName].filter(Boolean).join(" ") || x.name || x.email || x.customer?.firstName || x.id; }
function date(x: Row) { const v = x.createdAt || x.paymentDate || x.date || x.updatedAt; return v ? new Date(v).toLocaleString("en-NG") : "—"; }
function csvEscape(v: any) { return `"${String(v ?? "").replace(/"/g, '""')}"`; }

export default function AdminOverviewPage() {
  const [data, setData] = useState<Data>(empty); const [loading, setLoading] = useState(true); const [section, setSection] = useState<keyof Data>("customers");
  const [search, setSearch] = useState(""); const [type, setType] = useState(""); const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(50); const [pagination, setPagination] = useState({ page: 1, pageSize: 50, total: 0, totalPages: 1 }); const [error, setError] = useState("");

  async function load(nextPage = page) { setLoading(true); setError(""); try { const qs = new URLSearchParams({ section, search, type, from, to, page: String(nextPage), pageSize: String(pageSize) }); const result = await apiRequest(`/reports/operations?${qs.toString()}`); setData({ ...empty, ...result }); setPagination(result.pagination || { page: nextPage, pageSize, total: 0, totalPages: 1 }); } catch (e: any) { setError(e?.message || "Unable to load operational data."); } finally { setLoading(false); } }
  useEffect(() => { load(1); }, [section, type, from, to, pageSize]);
  useEffect(() => { const t = setTimeout(() => load(1), 350); return () => clearTimeout(t); }, [search]);

  const rows = data[section]; const totalAmount = rows.reduce((s, x) => s + Number(x.amount || 0), 0); const sections = useMemo(() => Object.keys(labels) as (keyof Data)[], []);
  function resetFilters() { setSearch(""); setType(""); setFrom(""); setTo(""); setPage(1); }
  function exportCsv() { const headers = ["Section", "Name/Record", "Amount", "Status/Type", "Reference", "Date"]; const body = rows.map(x => [labels[section], name(x), x.amount ?? "", x.status || x.type || "", x.reference || x.id || "", date(x)]); const csv = [headers, ...body].map(r => r.map(csvEscape).join(",")).join("\n"); const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `pwfb-${section}-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(url); }

  return <main style={{ maxWidth: 1500, margin: "0 auto", padding: "4px 0 40px" }}>
    <div className="pwfb-page-header" style={{ alignItems: "flex-start" }}><div><p className="pwfb-eyebrow">SUPER ADMIN • OPERATIONAL CONTROL</p><h1 className="pwfb-page-title">Operations Control Center</h1><p className="pwfb-page-description">Manage customers, loans, staff, savings and daily financial activity from the central operational workspace.</p></div><Link href="/dashboard" className="pwfb-secondary-button">← Dashboard</Link></div>

    <section className="pwfb-operation-control-center" aria-label="Operational Control Center">
      <div className="pwfb-operation-control-header"><div><span>OPERATIONAL CONTROL CENTER</span><h2>Core PWFB Operations</h2><p>Open an operational workspace directly from the control center.</p></div><strong>SUPER ADMIN</strong></div>
      <div className="pwfb-operation-control-grid">
        {sections.map(key => <Link key={key} href={operationLinks[key]} className="pwfb-operation-control-card"><span>{icons[key]}</span><div><strong>{labels[key]}</strong><small>{key === "customers" ? "Customer profiles & onboarding" : key === "loans" ? "Loans & repayments" : key === "staff" ? "Staff & access" : key === "savings" ? "Savings accounts & deposits" : key === "deposits" ? "Daily deposit activity" : key === "withdrawals" ? "Daily withdrawal activity" : "Customer & bank transfers"}</small></div><b>→</b></Link>)}
      </div>
    </section>

    <section style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12, marginBottom: 20 }}>{sections.map(key => <button key={key} type="button" onClick={() => { setSection(key); setPage(1); }} style={{ textAlign: "left", padding: 16, borderRadius: 14, border: section === key ? "2px solid #18863e" : "1px solid #e5e7eb", background: "#fff", boxShadow: section === key ? "0 4px 14px rgba(24,134,62,.10)" : "0 1px 2px rgba(16,24,40,.04)", cursor: "pointer" }}><div style={{ display: "flex", justifyContent: "space-between", color: "#667085", fontSize: 12, fontWeight: 700 }}><span>{labels[key]}</span><span style={{ fontSize: 18 }}>{icons[key]}</span></div><strong style={{ display: "block", fontSize: 25, marginTop: 8 }}>{loading ? "—" : pagination.total.toLocaleString()}</strong><small style={{ color: "#667085" }}>records</small></button>)}</section>

    <section className="pwfb-panel" style={{ marginBottom: 18 }}><div className="pwfb-panel-header"><div><h2>Operational filters</h2><p>Search and narrow the selected operational dataset.</p></div><span className="pwfb-record-count">{pagination.total.toLocaleString()} matching</span></div><div style={{ display: "grid", gridTemplateColumns: "minmax(220px,2fr) repeat(4,minmax(120px,1fr)) auto auto", gap: 10, alignItems: "end", padding: "0 18px 18px" }}><label>Search<input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Name, phone, email, ID, reference…" style={{ width: "100%", padding: 10, marginTop: 5, border: "1px solid #d0d5dd", borderRadius: 9 }} /></label><label>Type<select value={type} onChange={e => { setType(e.target.value); setPage(1); }} style={{ width: "100%", padding: 10, marginTop: 5, border: "1px solid #d0d5dd", borderRadius: 9, background: "#fff" }}><option value="">All</option><option value="DEPOSIT">Deposit</option><option value="WITHDRAWAL">Withdrawal</option><option value="TRANSFER_IN">Transfer In</option><option value="TRANSFER_OUT">Transfer Out</option></select></label><label>From<input type="date" value={from} onChange={e => { setFrom(e.target.value); setPage(1); }} style={{ width: "100%", padding: 10, marginTop: 5, border: "1px solid #d0d5dd", borderRadius: 9 }} /></label><label>To<input type="date" value={to} onChange={e => { setTo(e.target.value); setPage(1); }} style={{ width: "100%", padding: 10, marginTop: 5, border: "1px solid #d0d5dd", borderRadius: 9 }} /></label><label>Rows<select value={pageSize} onChange={e => setPageSize(Number(e.target.value))} style={{ width: "100%", padding: 10, marginTop: 5, border: "1px solid #d0d5dd", borderRadius: 9, background: "#fff" }}><option value="25">25</option><option value="50">50</option><option value="100">100</option><option value="200">200</option></select></label><button onClick={resetFilters} style={{ padding: 10, border: "1px solid #d0d5dd", borderRadius: 9, background: "#fff" }}>Reset</button><button onClick={exportCsv} disabled={loading || rows.length === 0} style={{ padding: 10, border: 0, borderRadius: 9, background: "#18863e", color: "#fff" }}>Export CSV</button></div></section>

    <section className="pwfb-panel" style={{ overflow: "hidden" }}><div className="pwfb-panel-header"><div><h2>{labels[section]}</h2><p>Operational records • {money(totalAmount)} represented on this page.</p></div>{error && <span style={{ color: "#b42318" }}>{error}</span>}</div>{loading ? <div className="pwfb-empty-state"><div className="pwfb-loading-dot" /><p>Loading operational records...</p></div> : rows.length === 0 ? <div className="pwfb-empty-state"><div className="pwfb-empty-icon">✓</div><h3>No records found</h3><p>No records match the current operational filters.</p></div> : <div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Record</th><th>Amount</th><th>Status / Type</th><th>Reference</th><th>Date</th><th>Action</th></tr></thead><tbody>{rows.map((x, i) => <tr key={x.id || i}><td><strong>{name(x)}</strong></td><td>{x.amount != null ? money(x.amount) : "—"}</td><td><span className="pwfb-status-badge">{x.status || x.type || "Recorded"}</span></td><td><code>{x.reference || x.id || "—"}</code></td><td>{date(x)}</td><td>{x.id && section === "customers" ? <Link href={`/customers/view/${x.id}`}>View</Link> : x.id && section === "loans" ? <Link href={`/loans/view/${x.id}`}>View</Link> : "—"}</td></tr>)}</tbody></table></div>}<div style={{ padding: 14, borderTop: "1px solid #eee", display: "flex", justifyContent: "space-between", alignItems: "center" }}><span>Page {pagination.page} of {pagination.totalPages}</span><div style={{ display: "flex", gap: 8 }}><button disabled={page <= 1 || loading} onClick={() => setPage(page - 1)} style={{ padding: "8px 13px" }}>Previous</button><button disabled={page >= pagination.totalPages || loading} onClick={() => setPage(page + 1)} style={{ padding: "8px 13px" }}>Next</button></div></div></section>
  </main>;
}
