import { Injectable, NotFoundException, BadRequestException } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateLoanDto } from './dto/create-loan.dto';
import { UpdateLoanDto } from './dto/update-loan.dto';
import { CreateGuarantorDto } from './dto/create-guarantor.dto';
const LOAN_TYPES = ['Loan','Daily Loan','Weekly Loan','Individual Loan','Monthly Loan'];
@Injectable()
export class LoansService {
 constructor(private readonly prisma: PrismaService) {}
 private async ensureLoanTables(){
  await this.prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PWFBLoanRate" ("id" TEXT PRIMARY KEY, "loanType" TEXT UNIQUE NOT NULL, "interestRate" DOUBLE PRECISION NOT NULL DEFAULT 0, "active" BOOLEAN NOT NULL DEFAULT TRUE, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
  await this.prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PWFBLoanMeta" ("loanId" TEXT PRIMARY KEY, "loanType" TEXT, "duration" DOUBLE PRECISION, "repaymentFrequency" TEXT, "purpose" TEXT, "interestAmount" DOUBLE PRECISION, "totalRepayment" DOUBLE PRECISION, "installmentAmount" DOUBLE PRECISION, "passportPhoto" TEXT, "disbursementDestination" TEXT, "verifiedNameMatchCount" DOUBLE PRECISION, "disbursementAccountVerified" BOOLEAN NOT NULL DEFAULT FALSE, "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`);
  await this.prisma.$executeRawUnsafe(`ALTER TABLE "PWFBLoanMeta" ADD COLUMN IF NOT EXISTS "disbursementDestination" TEXT`); await this.prisma.$executeRawUnsafe(`ALTER TABLE "PWFBLoanMeta" ADD COLUMN IF NOT EXISTS "verifiedNameMatchCount" DOUBLE PRECISION`); await this.prisma.$executeRawUnsafe(`ALTER TABLE "PWFBLoanMeta" ADD COLUMN IF NOT EXISTS "disbursementAccountVerified" BOOLEAN NOT NULL DEFAULT FALSE`);
  for(const type of LOAN_TYPES) await this.prisma.$executeRawUnsafe(`INSERT INTO "PWFBLoanRate" ("id","loanType","interestRate") VALUES ($1,$2,0) ON CONFLICT ("loanType") DO NOTHING`,`rate_${type.toLowerCase().replace(/[^a-z0-9]+/g,'_')}`,type);
 }
 private async meta(id:string){await this.ensureLoanTables();const rows=await this.prisma.$queryRawUnsafe<any[]>(`SELECT * FROM "PWFBLoanMeta" WHERE "loanId"=$1 LIMIT 1`,id);return rows[0]??null;}
 private async withMeta<T extends {id:string;amount:number;interestRate:number|null;repayments?:{amount:number}[]}>(loan:T){const meta=await this.meta(loan.id);const interestAmount=Number(meta?.interestAmount??(Number(loan.amount)*Number(loan.interestRate??0)/100));const totalRepayment=Number(meta?.totalRepayment??(Number(loan.amount)+interestAmount));const paidAmount=(loan.repayments??[]).reduce((s,r)=>s+Number(r.amount||0),0);return {...loan,...meta,interestAmount,totalRepayment,paidAmount,outstandingAmount:Math.max(0,totalRepayment-paidAmount)};}
 async getCustomerName(customerId:string){const customer=await this.prisma.customer.findUnique({where:{id:customerId}});if(!customer)throw new NotFoundException('Customer not found');return [customer.firstName,customer.middleName,customer.lastName].filter(Boolean).join(' ').trim();}
 async getLoanRates(){await this.ensureLoanTables();return this.prisma.$queryRawUnsafe<any[]>(`SELECT "loanType","interestRate","active","updatedAt" FROM "PWFBLoanRate" ORDER BY "loanType" ASC`);}
 async setLoanRate(loanType:string,interestRate:number){if(!LOAN_TYPES.includes(loanType))throw new NotFoundException('Unsupported loan type');if(!Number.isFinite(interestRate)||interestRate<0)throw new Error('Interest rate must be a non-negative number');await this.ensureLoanTables();const rows=await this.prisma.$queryRawUnsafe<any[]>(`UPDATE "PWFBLoanRate" SET "interestRate"=$1,"active"=TRUE,"updatedAt"=CURRENT_TIMESTAMP WHERE "loanType"=$2 RETURNING "loanType","interestRate","active","updatedAt"`,interestRate,loanType);return rows[0];}
 async create(dto:CreateLoanDto){const customer=await this.prisma.customer.findUnique({where:{id:dto.customerId}});if(!customer)throw new NotFoundException('Customer not found');await this.ensureLoanTables();const loanType=dto.loanType||'Loan';const destination=dto.disbursementDestination||'WALLET';if(destination==='BANK'&&(!dto.disbursementBankCode||!dto.disbursementAccountNumber||!dto.disbursementAccountName||dto.disbursementAccountVerified!==true||Number(dto.verifiedNameMatchCount||0)<2))throw new BadRequestException('Bank account must be verified with at least two matching names before loan submission');const rr=await this.prisma.$queryRawUnsafe<any[]>(`SELECT "interestRate" FROM "PWFBLoanRate" WHERE "loanType"=$1 AND "active"=TRUE LIMIT 1`,loanType);const interestRate=Number(rr[0]?.interestRate??dto.interestRate??0);const amount=Number(dto.amount||0);const interestAmount=amount*interestRate/100;const totalRepayment=amount+interestAmount;const duration=Math.max(1,Number(dto.duration||1));const installmentAmount=totalRepayment/duration;const loan=await this.prisma.loan.create({data:{customerId:dto.customerId,amount,interestRate,status:'PENDING',disbursementAmount:dto.disbursementAmount,disbursementAccountNumber:destination==='BANK'?dto.disbursementAccountNumber:null,disbursementAccountName:destination==='BANK'?dto.disbursementAccountName:null,disbursementBankCode:destination==='BANK'?dto.disbursementBankCode:null,disbursementBankName:destination==='BANK'?dto.disbursementBankName:null,disbursementUsesAlternativeAccount:destination==='BANK'},include:{customer:true,repayments:true,guarantors:true}});await this.prisma.$executeRawUnsafe(`INSERT INTO "PWFBLoanMeta" ("loanId","loanType","duration","repaymentFrequency","purpose","interestAmount","totalRepayment","installmentAmount","passportPhoto","disbursementDestination","verifiedNameMatchCount","disbursementAccountVerified") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,loan.id,loanType,duration,dto.repaymentFrequency??null,dto.purpose??null,interestAmount,totalRepayment,installmentAmount,dto.passportPhoto??null,destination,dto.verifiedNameMatchCount??0,destination==='BANK'&&dto.disbursementAccountVerified===true);return this.withMeta(loan);}
 async findAll(){const loans=await this.prisma.loan.findMany({orderBy:{createdAt:'desc'},include:{customer:{include:{bankAccounts:{where:{status:'ACTIVE'},include:{institution:true},orderBy:{isPrimary:'desc'}}}},repayments:true,guarantors:true}});return Promise.all(loans.map(l=>this.withMeta(l)));}
 async findOne(id:string){const loan=await this.prisma.loan.findUnique({where:{id},include:{customer:{include:{bankAccounts:{where:{status:'ACTIVE'},include:{institution:true},orderBy:{isPrimary:'desc'}}}},repayments:true,guarantors:true}});if(!loan)throw new NotFoundException('Loan not found');return this.withMeta(loan);}
 async update(id:string,dto:UpdateLoanDto){const existing=await this.findOne(id);if(dto.customerId){const customer=await this.prisma.customer.findUnique({where:{id:dto.customerId}});if(!customer)throw new NotFoundException('Customer not found');}const updated=await this.prisma.loan.update({where:{id},data:{customerId:dto.customerId,amount:dto.amount,interestRate:dto.interestRate,status:dto.status,disbursementAmount:dto.disbursementAmount,disbursementAccountNumber:dto.disbursementAccountNumber,disbursementAccountName:dto.disbursementAccountName,disbursementBankCode:dto.disbursementBankCode,disbursementBankName:dto.disbursementBankName,disbursementUsesAlternativeAccount:dto.disbursementUsesAlternativeAccount},include:{customer:true,repayments:true,guarantors:true}});await this.ensureLoanTables();const oldMeta=await this.meta(id);const amount=Number(updated.amount||0);const rate=Number(updated.interestRate??oldMeta?.interestRate??0);const interestAmount=amount*rate/100;const totalRepayment=amount+interestAmount;const duration=Math.max(1,Number(dto.duration??oldMeta?.duration??1));await this.prisma.$executeRawUnsafe(`INSERT INTO "PWFBLoanMeta" ("loanId","loanType","duration","repaymentFrequency","purpose","interestAmount","totalRepayment","installmentAmount","passportPhoto","disbursementDestination","verifiedNameMatchCount","disbursementAccountVerified") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) ON CONFLICT ("loanId") DO UPDATE SET "loanType"=COALESCE($2,"PWFBLoanMeta"."loanType"),"duration"=$3,"repaymentFrequency"=COALESCE($4,"PWFBLoanMeta"."repaymentFrequency"),"purpose"=COALESCE($5,"PWFBLoanMeta"."purpose"),"interestAmount"=$6,"totalRepayment"=$7,"installmentAmount"=$8,"passportPhoto"=COALESCE($9,"PWFBLoanMeta"."passportPhoto"),"disbursementDestination"=COALESCE($10,"PWFBLoanMeta"."disbursementDestination"),"verifiedNameMatchCount"=COALESCE($11,"PWFBLoanMeta"."verifiedNameMatchCount"),"disbursementAccountVerified"=COALESCE($12,"PWFBLoanMeta"."disbursementAccountVerified"),"updatedAt"=CURRENT_TIMESTAMP`,id,dto.loanType??oldMeta?.loanType??'Loan',duration,dto.repaymentFrequency??null,dto.purpose??null,interestAmount,totalRepayment,totalRepayment/duration,dto.passportPhoto??null,oldMeta?.disbursementDestination??'WALLET',oldMeta?.verifiedNameMatchCount??0,oldMeta?.disbursementAccountVerified??false);return this.withMeta(updated);}
 async remove(id:string){await this.findOne(id);await this.ensureLoanTables();await this.prisma.$executeRawUnsafe(`DELETE FROM "PWFBLoanMeta" WHERE "loanId"=$1`,id);return this.prisma.loan.delete({where:{id}});}
 async findGuarantors(loanId:string){await this.findOne(loanId);return this.prisma.guarantor.findMany({where:{loanId},orderBy:{createdAt:'desc'}});}
 async addGuarantor(loanId:string,dto:CreateGuarantorDto){await this.findOne(loanId);return this.prisma.guarantor.create({data:{loanId,firstName:dto.firstName,middleName:dto.middleName,lastName:dto.lastName,phone:dto.phone,email:dto.email,address:dto.address,dateOfBirth:dto.dateOfBirth?new Date(dto.dateOfBirth):undefined,relationship:dto.relationship,idType:dto.idType,idNumber:dto.idNumber,idDocument:dto.idDocument,passportPhoto:dto.passportPhoto,temporaryVerified:false,verificationNote:dto.verificationNote??'Temporary record only. Identity has not been externally verified.'}});}
 async updateGuarantor(loanId:string,guarantorId:string,dto:Partial<CreateGuarantorDto>){await this.findOne(loanId);const existing=await this.prisma.guarantor.findFirst({where:{id:guarantorId,loanId}});if(!existing)throw new NotFoundException('Guarantor not found');return this.prisma.guarantor.update({where:{id:guarantorId},data:{firstName:dto.firstName,middleName:dto.middleName,lastName:dto.lastName,phone:dto.phone,email:dto.email,address:dto.address,dateOfBirth:dto.dateOfBirth?new Date(dto.dateOfBirth):undefined,relationship:dto.relationship,idType:dto.idType,idNumber:dto.idNumber,idDocument:dto.idDocument,passportPhoto:dto.passportPhoto,verificationNote:dto.verificationNote}});}
 async removeGuarantor(loanId:string,guarantorId:string){await this.findOne(loanId);const existing=await this.prisma.guarantor.findFirst({where:{id:guarantorId,loanId}});if(!existing)throw new NotFoundException('Guarantor not found');return this.prisma.guarantor.delete({where:{id:guarantorId}});}
}
