"use client";
import { useEffect,useState } from "react";
import { apiRequest } from "../../lib/api";

type Wallet={id:string;staffId:string;branchId:string;balance:number;currency:string;firstName?:string;lastName?:string;position?:string;branchName?:string};
const money=(v:any)=>new Intl.NumberFormat("en-NG",{style:"currency",currency:"NGN",maximumFractionDigits:0}).format(Number(v)||0);
export default function StaffWalletPage(){const[wallets,setWallets]=useState<Wallet[]>([]),[staffId,setStaffId]=useState(""),[amount,setAmount]=useState(""),[mode,setMode]=useState<"issue"|"settle">("issue"),[reference,setReference]=useState(""),[description,setDescription]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function load(){try{setLoading(true);const d=await apiRequest("/staff-wallet");setWallets(Array.isArray(d)?d:[])}catch(e:any){setError(e?.message||"Unable to load staff wallets")}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setMessage("");if(!staffId||Number(amount)<=0)return setError("Select staff and enter a valid amount.");setSaving(true);try{await apiRequest(`/staff-wallet/${mode}`,{method:"POST",body:JSON.stringify({staffId,amount:Number(amount),reference:reference||undefined,description:description||undefined})});setMessage(mode==="issue"?"Field cash issued to staff wallet.":"Staff wallet settled successfully.");setAmount("");setReference("");setDescription("");await load()}catch(e:any){setError(e?.message||"Wallet operation failed")}finally{setSaving(false)}}
return <main className="min-h-screen bg-slate-50 p-4 text-slate-800 md:p-7"><div className="mx-auto max-w-6xl"><header className="mb-6 rounded-3xl bg-gradient-to-r from-orange-600 to-emerald-700 p-6 text-white shadow-lg"><p className="text-xs font-black tracking-[.2em] text-orange-100">FIELD CASH CONTROL</p><h1 className="text-3xl font-black">Staff Wallet</h1><p className="mt-1 text-sm">Money entrusted to field staff and money returned/used in field operations.</p></header>{error&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{error}</div>}{message&&<div className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{message}</div>}
<section className="mb-6 rounded-3xl bg-white p-5 shadow-sm"><h2 className="text-xl font-black text-emerald-900">Field cash movement</h2><div className="mt-4 grid gap-3 md:grid-cols-6"><select className="rounded-xl border p-3 md:col-span-2" value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="">Select staff wallet</option>{wallets.map(w=><option key={w.staffId} value={w.staffId}>{w.firstName} {w.lastName} — {w.position||"Staff"} ({money(w.balance)})</option>)}</select><div className="flex rounded-xl border p-1"><button type="button" onClick={()=>setMode("issue")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-black ${mode==="issue"?"bg-emerald-700 text-white":""}`}>Issue</button><button type="button" onClick={()=>setMode("settle")} className={`flex-1 rounded-lg px-3 py-2 text-sm font-black ${mode==="settle"?"bg-orange-600 text-white":""}`}>Settle</button></div><input className="rounded-xl border p-3" type="number" min="0" step="0.01" placeholder="Amount" value={amount} onChange={e=>setAmount(e.target.value)}/><input className="rounded-xl border p-3" placeholder="Reference" value={reference} onChange={e=>setReference(e.target.value)}/><input className="rounded-xl border p-3" placeholder="Description" value={description} onChange={e=>setDescription(e.target.value)}/><button onClick={submit} disabled={saving} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-black text-white disabled:opacity-50">{saving?"Saving…":mode==="issue"?"Issue Cash":"Settle Cash"}</button></div></section>
<section className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-black text-emerald-900">Field staff balances</h2><p className="text-xs text-slate-500">Collections settled from the Collections module automatically reduce the assigned staff wallet.</p></div><div className="overflow-x-auto"><table className="min-w-[800px] w-full text-sm"><thead className="bg-emerald-50 text-left text-xs uppercase text-emerald-900"><tr><th className="p-4">Staff</th><th className="p-4">Position</th><th className="p-4">Branch</th><th className="p-4">Wallet balance</th></tr></thead><tbody>{loading?<tr><td className="p-5" colSpan={4}>Loading…</td></tr>:wallets.map(w=><tr className="border-t" key={w.id}><td className="p-4 font-bold">{w.firstName} {w.lastName}</td><td className="p-4">{w.position||"—"}</td><td className="p-4">{w.branchName||"—"}</td><td className="p-4 text-lg font-black text-emerald-700">{money(w.balance)}</td></tr>)}</tbody></table></div></section></div></main>}
