'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { apiRequest } from '../../lib/api';

type Branch={id:string;name:string}; type Period={id:string;name:string;status:string}; type Check={branch:any;canSubmit:boolean;status:string;blockers:string[];checklist:Record<string,boolean>;totals:any};
const money=(n:any)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:2}).format(Number(n||0));
export default function BranchClosingPage(){
 const [branches,setBranches]=useState<Branch[]>([]),[periods,setPeriods]=useState<Period[]>([]),[branchId,setBranchId]=useState(''),[periodId,setPeriodId]=useState(''),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[check,setCheck]=useState<Check|null>(null),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){try{const [b,p,r]=await Promise.all([apiRequest('/branches'),apiRequest('/periods'),apiRequest('/branch-closing')]);setBranches(Array.isArray(b)?b:[]);setPeriods(Array.isArray(p)?p:[]);setRows(Array.isArray(r)?r:[]);if(!branchId&&Array.isArray(b)&&b[0])setBranchId(b[0].id);if(!periodId&&Array.isArray(p)){const open=p.find((x:any)=>x.status==='OPEN');if(open)setPeriodId(open.id)}}catch(e:any){setError(e.message||'Unable to load branch closing control.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function runCheck(){setError('');setCheck(null);if(!branchId||!periodId||!date){setError('Select a branch, financial period and closing date.');return}setBusy(true);try{setCheck(await apiRequest(`/branch-closing/${branchId}/checklist?periodId=${encodeURIComponent(periodId)}&closingDate=${encodeURIComponent(date)}`))}catch(e:any){setError(e.message||'Unable to run closing checklist.')}finally{setBusy(false)}}
 async function submit(){if(!check?.canSubmit)return;setBusy(true);try{await apiRequest(`/branch-closing/${branchId}/submit`,{method:'POST',body:JSON.stringify({periodId,closingDate:date})});await load();await runCheck()}catch(e:any){setError(e.message||'Unable to submit branch closing.')}finally{setBusy(false)}}
 async function approve(id:string){setBusy(true);try{await apiRequest(`/branch-closing/${id}/approve`,{method:'POST'});await load()}catch(e:any){setError(e.message||'Unable to finalize branch closing.')}finally{setBusy(false)}}
 return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">BRANCH OPERATIONS</p><h1 className="pwfb-page-title">Branch End-of-Day Settlement</h1><p className="pwfb-page-description">Complete the branch settlement checklist before submitting the day for final approval.</p></div><Link href="/reconciliation" className="pwfb-secondary-button">Reconciliation →</Link></div>{error&&<div className="pwfb-alert">{error}</div>}
 <section className="pwfb-panel"><div className="form"><label>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Financial Period<select value={periodId} onChange={e=>setPeriodId(e.target.value)}>{periods.map(p=><option key={p.id} value={p.id}>{p.name} • {p.status}</option>)}</select></label><label>Closing Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><button className="pwfb-primary-button" onClick={runCheck} disabled={busy||loading}>{busy?'Working…':'Run Settlement Check'}</button></div></section>
 {check&&<><section className="pwfb-stat-grid"><div className="pwfb-stat-card"><span>Collections</span><strong>{money(check.totals.collections)}</strong><small>Daily collections</small></div><div className="pwfb-stat-card"><span>Staff Wallet</span><strong>{money(check.totals.staffWalletBalance)}</strong><small>Must settle to ₦0</small></div><div className="pwfb-stat-card pwfb-stat-orange"><span>Closing Cash</span><strong>{money(check.totals.closingCash)}</strong><small>Cash in − cash out</small></div></section><section className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Closing Checklist</h2><p>{check.status==='READY'?'All mandatory branch controls are clear.':'Resolve the following controls before submission.'}</p></div><span className={check.canSubmit?'ready':'blocked'}>{check.canSubmit?'READY':'REVIEW REQUIRED'}</span></div><div className="checks">{Object.entries(check.checklist).map(([k,v])=><div key={k} className={v?'ok':'bad'}>{v?'✓':'✕'} {k.replaceAll(/([A-Z])/g,' $1')}</div>)}</div>{check.blockers.length>0&&<div className="blockers"><strong>Blockers:</strong> {check.blockers.join(', ')}</div>}{check.canSubmit&&<button className="pwfb-primary-button" onClick={submit} disabled={busy}>Submit Branch Closing</button>}</section></>}
 <section className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Branch Closing Register</h2><p>Submitted and finalized branch settlement records.</p></div><span className="pwfb-record-count">{rows.length} records</span></div><div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Branch</th><th>Date</th><th>Status</th><th>Submitted</th><th>Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.branchName}</td><td>{String(r.closingDate).slice(0,10)}</td><td>{r.status}</td><td>{r.submittedBy||'—'}</td><td>{r.status==='SUBMITTED'?<button className="pwfb-secondary-button" onClick={()=>approve(r.id)} disabled={busy}>Finalize</button>:'Closed'}</td></tr>)}{!rows.length&&!loading&&<tr><td colSpan={5}>No branch closings recorded yet.</td></tr>}</tbody></table></div></section>
 <style jsx>{`.form{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}label{display:flex;flex-direction:column;gap:7px;font-size:13px;font-weight:800;color:#475569}select,input{padding:11px;border:1px solid #d7dee8;border-radius:10px;background:#fff;font:inherit}.checks{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.ok,.bad{padding:12px;border-radius:10px;font-weight:800;font-size:13px}.ok{background:#eef8f1;color:#17633f}.bad{background:#fff2ef;color:#9b493b}.ready,.blocked{padding:8px 12px;border-radius:999px;font-size:11px;font-weight:900}.ready{background:#eaf7ef;color:#17633f}.blocked{background:#fff0ed;color:#a0473a}.blockers{margin:14px 0;padding:12px;border-radius:10px;background:#fff7e8;color:#7a5310}@media(max-width:850px){.form{grid-template-columns:1fr}}`}</style></main>;
}