import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';
import { CreateRepaymentDto } from './dto/create-repayment.dto';
import { UpdateRepaymentDto } from './dto/update-repayment.dto';

@Injectable()
export class RepaymentsService {
  constructor(private readonly prisma: PrismaService) {}
  private amount(value: unknown) { const n=Number(value); if(!Number.isFinite(n)||n<=0) throw new BadRequestException('Repayment amount must be greater than zero'); return Math.round(n*100)/100; }
  private async ensureAllocationTable(tx:any=this.prisma) { await tx.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "PWFBRepaymentAllocation" ("repaymentId" TEXT PRIMARY KEY,"principalPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,"interestPaid" DOUBLE PRECISION NOT NULL DEFAULT 0,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)`); }
  private async allocate(tx:any,loanId:string,repaymentId:string,amount:number) {
    const loan=await tx.loan.findUnique({where:{id:loanId}}); if(!loan) throw new NotFoundException('Loan not found');
    const interestAmount=Number(loan.amount||0)*Number(loan.interestRate||0)/100;
    const prior=await tx.$queryRawUnsafe(`SELECT COALESCE(SUM("interestPaid"),0) AS "interestPaid", COALESCE(SUM("principalPaid"),0) AS "principalPaid" FROM "PWFBRepaymentAllocation" a JOIN "Repayment" r ON r.id=a."repaymentId" WHERE r."loanId"=$1 AND r.id<>$2`,loanId,repaymentId) as Array<{interestPaid:number|string;principalPaid:number|string}>;
    const priorInterest=Number(prior[0]?.interestPaid||0), priorPrincipal=Number(prior[0]?.principalPaid||0);
    const interestRemaining=Math.max(0,interestAmount-priorInterest), principalRemaining=Math.max(0,Number(loan.amount||0)-priorPrincipal);
    const interestPaid=Math.min(amount,interestRemaining), principalPaid=Math.min(Math.max(0,amount-interestPaid),principalRemaining);
    const allocated=Math.round((interestPaid+principalPaid)*100)/100;
    if(allocated<Math.round(amount*100)/100) throw new BadRequestException(`Repayment exceeds the outstanding loan balance. Outstanding: ₦${(interestRemaining+principalRemaining).toFixed(2)}`);
    await tx.$executeRawUnsafe(`INSERT INTO "PWFBRepaymentAllocation" ("repaymentId","principalPaid","interestPaid","updatedAt") VALUES ($1,$2,$3,CURRENT_TIMESTAMP) ON CONFLICT ("repaymentId") DO UPDATE SET "principalPaid"=$2,"interestPaid"=$3,"updatedAt"=CURRENT_TIMESTAMP`,repaymentId,principalPaid,interestPaid);
    return {principalPaid,interestPaid,principalOutstanding:Math.max(0,principalRemaining-principalPaid),interestOutstanding:Math.max(0,interestRemaining-interestPaid)};
  }
  async create(dto:CreateRepaymentDto) { const amount=this.amount(dto.amount); const loan=await this.prisma.loan.findUnique({where:{id:dto.loanId}}); if(!loan) throw new NotFoundException('Loan not found'); await this.ensureAllocationTable(); return this.prisma.$transaction(async tx=>{const repayment=await tx.repayment.create({data:{loanId:dto.loanId,amount,paymentDate:dto.paymentDate?new Date(dto.paymentDate):undefined,method:dto.method,notes:dto.notes},include:{loan:{include:{customer:true}}}}); const allocation=await this.allocate(tx,loan.id,repayment.id,amount); await tx.transaction.create({data:{customerId:loan.customerId,type:'LOAN_REPAYMENT',amount,description:`Loan repayment — ${loan.id}${dto.method?` — ${dto.method}`:''} — Interest ₦${allocation.interestPaid.toFixed(2)} / Principal ₦${allocation.principalPaid.toFixed(2)}`}}); return {...repayment,...allocation};}); }
  async findAll(){await this.ensureAllocationTable(); const rows=await this.prisma.repayment.findMany({orderBy:{createdAt:'desc'},include:{loan:{include:{customer:true}}}}); return Promise.all(rows.map(async repayment=>{const allocation=await this.prisma.$queryRawUnsafe(`SELECT "principalPaid","interestPaid" FROM "PWFBRepaymentAllocation" WHERE "repaymentId"=$1`,repayment.id) as Array<{principalPaid:number|string;interestPaid:number|string}>; return {...repayment,principalPaid:Number(allocation[0]?.principalPaid||0),interestPaid:Number(allocation[0]?.interestPaid||0)};}));}
  async findOne(id:string){await this.ensureAllocationTable(); const repayment=await this.prisma.repayment.findUnique({where:{id},include:{loan:{include:{customer:true}}}}); if(!repayment) throw new NotFoundException('Repayment not found'); const allocation=await this.prisma.$queryRawUnsafe(`SELECT "principalPaid","interestPaid" FROM "PWFBRepaymentAllocation" WHERE "repaymentId"=$1`,id) as Array<{principalPaid:number|string;interestPaid:number|string}>; return {...repayment,principalPaid:Number(allocation[0]?.principalPaid||0),interestPaid:Number(allocation[0]?.interestPaid||0)};}
  async update(id:string,dto:UpdateRepaymentDto){const existing=await this.findOne(id); if(dto.loanId&&dto.loanId!==existing.loanId) throw new BadRequestException('A repayment cannot be moved to another loan. Create a reversal and a new repayment instead.'); const newAmount=dto.amount===undefined?Number(existing.amount):this.amount(dto.amount),oldAmount=Number(existing.amount),delta=Math.round((newAmount-oldAmount)*100)/100; return this.prisma.$transaction(async tx=>{const repayment=await tx.repayment.update({where:{id},data:{amount:newAmount,paymentDate:dto.paymentDate?new Date(dto.paymentDate):undefined,method:dto.method,notes:dto.notes},include:{loan:{include:{customer:true}}}}); const allocation=await this.allocate(tx,existing.loanId,id,newAmount); if(delta!==0) await tx.transaction.create({data:{customerId:existing.loan.customerId,type:delta>0?'LOAN_REPAYMENT_ADJUSTMENT':'LOAN_REPAYMENT_REVERSAL',amount:Math.abs(delta),description:`Repayment ${id} amount correction from ${oldAmount} to ${newAmount} — Interest ₦${allocation.interestPaid.toFixed(2)} / Principal ₦${allocation.principalPaid.toFixed(2)}`}}); return {...repayment,...allocation};});}
  async remove(id:string){const existing=await this.findOne(id); return this.prisma.$transaction(async tx=>{const deleted=await tx.repayment.delete({where:{id}}); await tx.$executeRawUnsafe(`DELETE FROM "PWFBRepaymentAllocation" WHERE "repaymentId"=$1`,id); await tx.transaction.create({data:{customerId:existing.loan.customerId,type:'LOAN_REPAYMENT_REVERSAL',amount:Number(existing.amount),description:`Reversal of deleted loan repayment ${id} — Interest ₦${Number(existing.interestPaid||0).toFixed(2)} / Principal ₦${Number(existing.principalPaid||0).toFixed(2)}`}}); return deleted;});}
}
