"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "../../lib/api";

type Period={id:string;name:string;status:string};
type Snapshot={period:any;scope:any;status:string;controls:any;exceptions:any[]};
const money=(n:any)=>`₦${Number(n||0).toLocaleString("en-NG",{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function ReconciliationPage(){
 const [periods,setPeriods]=useState<Period[]>([]); const [periodId,setPeriodId]=useState(""); const [branchId,setBranchId]=useState(""); const [branches,setBranches]=useState<any[]>([]); const [data,setData]=useState<Snapshot|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{const q=new URLSearchParams();if(periodId)q.set("periodId",periodId);if(branchId)q.set("branchId",branchId);setData(await apiRequest(`/reconciliation/summary?${q.toString()}`));}catch(e:any){setError(e?.message||"Unable to load reconciliation.");}finally{setLoading(false)}}
 useEffect(()=>{(async()=>{try{const [p,b]=await Promise.all([apiRequest("/periods"),apiRequest("/branches")]);setPeriods(Array.isArray(p)?p:[]);setBranches(Array.isArray(b)?b:[]);const open=(p||[]).find((x:any)=>x.status==="OPEN");if(open)setPeriodId(open.id);}catch(e:any){setError(e?.message||"Unable to load controls.");}})()},[]);
 useEffect(()=>{load()},[periodId,branchId]);
 const c=data?.controls;
 return <main style={{padding:"28px",maxWidth:1400,margin:"0 auto"}}>
  <div style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap",alignItems:"center"}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1,color:"#ef7d22"}}>SUPER ADMIN • FINANCE CONTROL</div><h1 style={{fontSize:32,margin:"6px 0"}}>End-to-End Reconciliation Control</h1><p style={{color:"#65736b",margin:0}}>Review operational money movement before a financial period is closed.</p></div><div style={{display:"flex",gap:8}}><Link href="/cashbook" className="pwfb-btn-secondary">Cashbook</Link><Link href="/collections" className="pwfb-btn-primary">Collections</Link></div></div>
  <section style={{display:"flex",gap:12,flexWrap:"wrap",margin:"24px 0"}}><select value={periodId} onChange={e=>setPeriodId(e.target.value)} style={{padding:12,borderRadius:10,border:"1px solid #d9e1dc",minWidth:220}}><option value="">All financial periods</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} • {p.status}</option>)}</select><select value={branchId} onChange={e=>setBranchId(e.target.value)} style={{padding:12,borderRadius:10,border:"1px solid #d9e1dc",minWidth:220}}><option value="">All accessible branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><button onClick={load} style={{padding:"12px 18px",border:0,borderRadius:10,background:"#16864a",color:"#fff",fontWeight:800}}>Refresh</button></section>
  {error&&<div style={{padding:14,borderRadius:12,background:"#fff2f0",color:"#a33",marginBottom:18}}>{error}</div>}
  {loading?<p>Loading live reconciliation…</p>:data&&<>
   <div style={{padding:18,borderRadius:16,background:data.status==="CLEAR"?"#edf9f1":"#fff8e9",border:"1px solid #dce6df",marginBottom:18}}><strong>{data.status==="CLEAR"?"RECONCILIATION CLEAR":"REVIEW REQUIRED"}</strong><span style={{marginLeft:10,color:"#65736b"}}>{data.status==="CLEAR"?"No unreconciled collections are currently detected in this scope.":`${data.exceptions.length} collection record(s) still require reconciliation.`}</span></div>
   <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{[
    ["Collections",money(c.collections.amount),`${c.collections.count} records`],["Unreconciled",money(c.collections.unreconciledAmount),`${c.collections.count-c.collections.reconciledCount} records`],["Cashbook Balance",money(c.cashbook.balance),`${c.cashbook.entries} entries`],["Staff Wallet",money(c.staffWallet.balance),`${c.staffWallet.wallets} wallets`],["Savings",money(c.savings.amount),`${c.savings.records} records`],["Repayments",money(c.repayments.amount),`${c.repayments.records} records`],["Loans",money(c.loans.amount),`${c.loans.records} records`],["Payroll Paid",money(c.payroll.netPaid),`${c.payroll.paidRuns} paid runs`]
   ].map(([a,b,d])=><div key={a} style={{background:"#fff",border:"1px solid #e0e6e2",borderRadius:16,padding:18}}><small style={{color:"#718078"}}>{a}</small><strong style={{display:"block",fontSize:22,margin:"7px 0"}}>{b}</strong><span style={{fontSize:12,color:"#718078"}}>{d}</span></div>)}</section>
   <section style={{marginTop:22,background:"#fff",border:"1px solid #e0e6e2",borderRadius:16,padding:18}}><div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px"}}>Reconciliation Exceptions</h2><p style={{margin:0,color:"#718078"}}>Unreconciled daily collections are surfaced here for operational review.</p></div><Link href="/collections" className="pwfb-btn-secondary">Open Collections</Link></div>{data.exceptions.length===0?<p style={{padding:"24px 0",color:"#16864a",fontWeight:700}}>No exceptions in the selected scope.</p>:<div style={{overflowX:"auto",marginTop:14}}><table style={{width:"100%",borderCollapse:"collapse"}}><thead><tr>{["Date","Type","Customer","Staff","Branch","Amount","Status","Reference"].map(x=><th key={x} style={{textAlign:"left",padding:10,borderBottom:"1px solid #e4e9e6",fontSize:12}}>{x}</th>)}</tr></thead><tbody>{data.exceptions.map(x=><tr key={x.id}>{[new Date(x.date).toLocaleDateString(),x.type,x.customer||"—",x.staff||"—",x.branch||"—",money(x.amount),x.settled?"Settled":"Unsettled",x.reference||x.id].map((v,i)=><td key={i} style={{padding:10,borderBottom:"1px solid #eef1ef",fontSize:13}}>{v}</td>)}</tr>)}</tbody></table></div>}</section>
   <section style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:18}}>{[["Staff Wallet","/staff-wallet"],["Savings","/savings"],["Loans","/loans"],["Payroll","/payroll"],["Approvals","/approvals"],["Reports","/reports"]].map(([x,h])=><Link key={h} href={h} className="pwfb-btn-secondary">{x}</Link>)}</section>
  </>}
 </main>
}
