FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache wget

COPY . .

RUN npm install

WORKDIR /app/apps/backend

RUN npx prisma generate

RUN npm run build

EXPOSE 3000

HEALTHCHECK \
  --interval=30s \
  --timeout=5s \
  --start-period=20s \
  --retries=3 \
  CMD wget -qO- http://localhost:3000/health || exit 1

CMD ["npm", "run", "start:prod"]
