FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY apps/backend ./apps/backend
COPY packages ./packages

WORKDIR /app/apps/backend

RUN npm run build

EXPOSE 3000

HEALTHCHECK \
  --interval=30s \
  --timeout=5s \
  --start-period=20s \
  --retries=3 \
  CMD wget -qO- http://localhost:3000/health || exit 1

CMD ["node", "dist/main.js"]
