"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useSearchParams } from "next/navigation";
import { apiRequest } from "../../lib/api";

type Branch={id:string;name:string};
type Period={id:string;name:string;status?:string};
type Row={id:string;entryDate:string;description?:string;narration?:string;referenceNo?:string;branch?:{name?:string};period?:{name?:string};totalAmount?:number;[key:string]:any};
const receipts=[['previousCashAtHand','Previous Cash at Hand'],['dailyCashInHand','Daily Cash In-Hand'],['savingsDeposits','Savings Deposits'],['dailyInstallmentCollection','Daily Installment Collection'],['monthlyCollection','Monthly Collection'],['memberRegistration','Member Registration'],['riskPremium','Risk Premium'],['passbookSales','Passbook Sales']] as const;
const payments=[['loanDisbursement','Loan Disbursement'],['bankDeposit','Bank Deposit'],['savingsWithdrawal','Savings Withdrawal'],['savingsReturnedAdjustment','Savings Returned / Adjustment'],['fundTransfer','Fund Transfer'],['other','Other']] as const;
const allFields=[...receipts,...payments].map(x=>x[0]);
const makeBlank=()=>{const x:any={entryDate:new Date().toISOString().slice(0,10),description:'',narration:'',referenceNo:''};for(const k of allFields)x[k]='0';return x};
const money=(v:any)=>new Intl.NumberFormat('en-NG',{style:'currency',currency:'NGN',maximumFractionDigits:0}).format(Number(v)||0);
const num=(v:any)=>Math.max(0,Number(v)||0);

export default function CashbookPage(){
 const searchParams=useSearchParams();
 const [branches,setBranches]=useState<Branch[]>([]),[periods,setPeriods]=useState<Period[]>([]),[branchId,setBranchId]=useState(''),[periodId,setPeriodId]=useState('');
 const [rows,setRows]=useState<Row[]>([]),[form,setForm]=useState<any>(makeBlank()),[editingId,setEditingId]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[query,setQuery]=useState('');
 const receiptTotal=useMemo(()=>receipts.reduce((s,[k])=>s+num(form[k]),0),[form]);
 const paymentTotal=useMemo(()=>payments.reduce((s,[k])=>s+num(form[k]),0),[form]);
 const net=receiptTotal-paymentTotal;
 async function loadBase(){try{const [b,p]=await Promise.all([apiRequest('/branches'),apiRequest('/periods')]);const bs=Array.isArray(b)?b:[],ps=Array.isArray(p)?p:[];setBranches(bs);setPeriods(ps);if(!branchId&&bs[0])setBranchId(bs[0].id);if(!periodId){const open=ps.find((x:Period)=>x.status==='OPEN')||ps[0];if(open)setPeriodId(open.id);}}catch(e:any){setError(e?.message||'Unable to load Cash Book settings.')}}
 async function loadRows(){try{setLoading(true);setError('');const q=new URLSearchParams();if(periodId)q.set('periodId',periodId);if(branchId)q.set('branchId',branchId);if(from)q.set('from',from);if(to)q.set('to',`${to}T23:59:59`);const data=await apiRequest(`/cashbook/daily?${q}`);setRows(Array.isArray(data)?data:[]);}catch(e:any){setError(e?.message||'Unable to load Cash Book.')}finally{setLoading(false)}}
 useEffect(()=>{void loadBase()},[]); useEffect(()=>{if(periodId||branchId)void loadRows()},[periodId,branchId,from,to]);
 useEffect(()=>{const id=searchParams.get('edit');if(id&&rows.length){const r=rows.find(x=>x.id===id);if(r)edit(r)}},[searchParams,rows]);
 function setField(k:string,v:string){setForm((f:any)=>({...f,[k]:v}))}
 function edit(r:Row){const next:any={...makeBlank(),entryDate:new Date(r.entryDate).toISOString().slice(0,10),description:r.description||'',narration:r.narration||'',referenceNo:r.referenceNo||''};for(const k of allFields)next[k]=String(r[k]??0);setForm(next);setEditingId(r.id);window.scrollTo({top:0,behavior:'smooth'})}
 function reset(){setEditingId(null);setForm(makeBlank())}
 async function submit(e:React.FormEvent){e.preventDefault();if(!periodId||!branchId)return;if(receiptTotal+paymentTotal<=0){setError('Enter at least one cashbook amount.');return}setSaving(true);setError('');setMessage('');try{const payload:any={periodId,branchId,entryDate:form.entryDate,description:form.description,narration:form.narration,referenceNo:form.referenceNo};for(const k of allFields)payload[k]=num(form[k]);if(editingId)await apiRequest(`/cashbook/daily/${editingId}`,{method:'PATCH',body:JSON.stringify(payload)});else await apiRequest('/cashbook/daily',{method:'POST',body:JSON.stringify(payload)});setMessage(editingId?'Cash Book entry updated successfully.':'Cash Book entry posted successfully.');reset();await loadRows()}catch(e:any){setError(e?.message||'Unable to save Cash Book entry.')}finally{setSaving(false)}}
 async function remove(id:string){if(!confirm('Delete this Cash Book entry?'))return;try{await apiRequest(`/cashbook/daily/${id}`,{method:'DELETE'});setMessage('Cash Book entry deleted.');await loadRows()}catch(e:any){setError(e?.message||'Unable to delete entry.')}}
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?rows.filter(r=>[r.description,r.narration,r.referenceNo,r.branch?.name].some(v=>String(v||'').toLowerCase().includes(q))):rows},[rows,query]);
 const totals=useMemo(()=>({in:filtered.reduce((s,r)=>s+receipts.reduce((x,[k])=>x+num(r[k]),0),0),out:filtered.reduce((s,r)=>s+payments.reduce((x,[k])=>x+num(r[k]),0),0)}),[filtered]);
 return <main className="min-h-screen bg-slate-50 text-slate-800 p-4 md:p-7"><div className="mx-auto max-w-[1500px]">
  <header className="mb-6 rounded-3xl bg-gradient-to-r from-emerald-800 to-emerald-600 p-6 text-white shadow-lg"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black tracking-[.2em] text-orange-300">PWFB FINANCE OPERATIONS</p><h1 className="mt-1 text-3xl font-black">Cash Book</h1><p className="mt-2 max-w-2xl text-sm text-emerald-50">Official branch cash ledger for receipts, payments, daily cash movement and audit history.</p></div><div className="flex gap-2"><Link href="/dashboard" className="rounded-xl bg-white/10 px-4 py-2 text-sm font-bold hover:bg-white/20">Dashboard</Link><Link href="/staff-wallet/history" className="rounded-xl bg-orange-500 px-4 py-2 text-sm font-bold text-white">History</Link></div></div></header>
  {error&&<div className="mb-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-medium text-red-700">{error}</div>}{message&&<div className="mb-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-800">{message}</div>}
  <section className="mb-5 grid gap-4 md:grid-cols-4"><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-500">RECEIPTS / CASH IN</p><strong className="mt-2 block text-2xl text-emerald-700">{money(totals.in)}</strong></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-500">PAYMENTS / CASH OUT</p><strong className="mt-2 block text-2xl text-orange-600">{money(totals.out)}</strong></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-500">NET MOVEMENT</p><strong className={`mt-2 block text-2xl ${totals.in-totals.out>=0?'text-emerald-700':'text-red-600'}`}>{money(totals.in-totals.out)}</strong></div><div className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs font-bold text-slate-500">POSTED ENTRIES</p><strong className="mt-2 block text-2xl text-emerald-900">{filtered.length}</strong></div></section>
  <section className="mb-6 overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b border-slate-100 bg-emerald-50 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-widest text-orange-600">{editingId?'EDIT POSTED ENTRY':'POST NEW ENTRY'}</p><h2 className="text-xl font-black text-emerald-900">Daily Cash Book Posting</h2></div><div className="rounded-xl bg-white px-4 py-2 text-right shadow-sm"><span className="block text-[10px] font-bold text-slate-500">NET ENTRY</span><strong className={net>=0?'text-emerald-700':'text-orange-600'}>{money(net)}</strong></div></div></div>
   <form onSubmit={submit} className="p-5"><div className="grid gap-3 md:grid-cols-4"><label className="text-xs font-bold text-slate-600">ENTRY DATE<input className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="date" value={form.entryDate} onChange={e=>setField('entryDate',e.target.value)} required/></label><label className="text-xs font-bold text-slate-600">FINANCIAL PERIOD<select className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" value={periodId} onChange={e=>setPeriodId(e.target.value)} required><option value="">Select period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name} {p.status==='CLOSED'?'— CLOSED':''}</option>)}</select></label><label className="text-xs font-bold text-slate-600">BRANCH<select className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" value={branchId} onChange={e=>setBranchId(e.target.value)} required><option value="">Select branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className="text-xs font-bold text-slate-600">REFERENCE NO.<input className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" value={form.referenceNo} onChange={e=>setField('referenceNo',e.target.value)} placeholder="Receipt / voucher reference"/></label></div>
   <div className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl border border-emerald-100"><div className="border-b border-emerald-100 bg-emerald-50 p-4"><h3 className="font-black text-emerald-900">Receipts & Cash In</h3><p className="text-xs text-slate-500">Money received or brought into the branch cash position.</p></div><div className="grid gap-3 p-4 sm:grid-cols-2">{receipts.map(([k,l])=><label key={k} className="text-xs font-bold text-slate-600">{l}<input className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="number" min="0" step="0.01" value={form[k]} onChange={e=>setField(k,e.target.value)}/></label>)}</div></div><div className="rounded-2xl border border-orange-100"><div className="border-b border-orange-100 bg-orange-50 p-4"><h3 className="font-black text-orange-700">Payments & Cash Out</h3><p className="text-xs text-slate-500">Money paid, deposited, transferred or otherwise leaving cash.</p></div><div className="grid gap-3 p-4 sm:grid-cols-2">{payments.map(([k,l])=><label key={k} className="text-xs font-bold text-slate-600">{l}<input className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" type="number" min="0" step="0.01" value={form[k]} onChange={e=>setField(k,e.target.value)}/></label>)}</div></div></div>
   <div className="mt-5 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold text-slate-600">DESCRIPTION<input className="mt-1 w-full rounded-xl border border-slate-200 p-3 text-sm" value={form.description} onChange={e=>setField('description',e.target.value)} placeholder="What is this posting for?"/></label><label className="text-xs font-bold text-slate-600">NARRATION<textarea className="mt-1 min-h-12 w-full rounded-xl border border-slate-200 p-3 text-sm" value={form.narration} onChange={e=>setField('narration',e.target.value)} placeholder="Additional audit narration"/></label></div>
   <div className="mt-5 flex flex-wrap justify-end gap-2"><button type="button" onClick={reset} className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-slate-700">Clear</button>{editingId&&<button type="button" onClick={reset} className="rounded-xl border border-orange-200 bg-orange-50 px-5 py-3 text-sm font-bold text-orange-700">Cancel Edit</button>}<button type="submit" disabled={saving||!periodId||!branchId} className="rounded-xl bg-emerald-700 px-6 py-3 text-sm font-black text-white shadow-sm hover:bg-emerald-800 disabled:opacity-50">{saving?'Posting…':editingId?'Update Cash Book':'Post Cash Book Entry'}</button></div></form>
  </section>
  <section className="overflow-hidden rounded-3xl bg-white shadow-sm"><div className="border-b border-slate-100 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black tracking-widest text-orange-600">AUDIT LEDGER</p><h2 className="text-xl font-black text-emerald-900">Posted Cash Book History</h2><p className="text-xs text-slate-500">Credit Officers and authorized finance staff can review the same branch ledger here.</p></div><div className="flex flex-wrap gap-2"><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search reference, description…"/><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className="rounded-xl border border-slate-200 px-3 py-2 text-sm" type="date" value={to} onChange={e=>setTo(e.target.value)}/></div></div></div>
   <div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-sm"><thead className="bg-emerald-50 text-left text-xs uppercase tracking-wide text-emerald-900"><tr><th className="p-3">Date</th><th className="p-3">Branch</th><th className="p-3">Description</th><th className="p-3">Reference</th><th className="p-3 text-right">Cash In</th><th className="p-3 text-right">Cash Out</th><th className="p-3 text-right">Net</th><th className="p-3">Actions</th></tr></thead><tbody>{filtered.map(r=>{const ci=receipts.reduce((s,[k])=>s+num(r[k]),0),co=payments.reduce((s,[k])=>s+num(r[k]),0);return <tr key={r.id} className="border-t border-slate-100 hover:bg-slate-50"><td className="p-3 whitespace-nowrap">{new Date(r.entryDate).toLocaleDateString('en-NG')}</td><td className="p-3">{r.branch?.name||'—'}</td><td className="p-3 font-medium">{r.description||r.narration||'—'}</td><td className="p-3">{r.referenceNo||'—'}</td><td className="p-3 text-right font-bold text-emerald-700">{money(ci)}</td><td className="p-3 text-right font-bold text-orange-600">{money(co)}</td><td className={`p-3 text-right font-black ${ci-co>=0?'text-emerald-700':'text-red-600'}`}>{money(ci-co)}</td><td className="p-3"><div className="flex gap-2"><button type="button" onClick={()=>edit(r)} className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-bold">Edit</button><button type="button" onClick={()=>remove(r.id)} className="rounded-lg border border-red-200 bg-red-50 px-3 py-1.5 text-xs font-bold text-red-700">Delete</button></div></td></tr>})}{loading&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">Loading Cash Book…</td></tr>}{!loading&&!filtered.length&&<tr><td colSpan={8} className="p-10 text-center text-slate-500">No Cash Book entries found.</td></tr>}</tbody></table></div></section>
 </div></main>;
}
