'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { apiRequest } from '../../../lib/api';

type Staff = { id:string; staffId?:string; firstName?:string; middleName?:string; lastName?:string; email?:string; phone?:string; position?:string; employmentStatus?:string; department?:{name?:string}; branch?:{id?:string;name?:string}; region?:{id?:string;name?:string}; division?:{id?:string;name?:string}; area?:{id?:string;name?:string}; user?:{role?:string}; assignments?:Assignment[] };
type Assignment = { id:string; role:string; active?:boolean; startsAt?:string; endsAt?:string; notes?:string; region?:{name?:string}; division?:{name?:string}; area?:{name?:string}; branch?:{name?:string} };
type Node = { id:string; name:string; regionId?:string; divisionId?:string; areaId?:string };
type Region = Node & { divisions?:Node[]; areas?:Node[]; branches?:Node[] };
const roles=['SUPER_ADMIN','ADMIN','REGIONAL_MANAGER','DIVISIONAL_MANAGER','MONITORING_TEAM','AUDITOR','AREA_MANAGER','BRANCH_MANAGER','CREDIT_OFFICER','TELLER','LOAN_OFFICER','STAFF'];

export default function StaffWorkspace(){
 const params=useParams<{id:string}>(); const id=params.id;
 const [staff,setStaff]=useState<Staff|null>(null); const [regions,setRegions]=useState<Region[]>([]); const [role,setRole]=useState(''); const [regionId,setRegionId]=useState(''); const [divisionId,setDivisionId]=useState(''); const [areaId,setAreaId]=useState(''); const [branchId,setBranchId]=useState(''); const [notes,setNotes]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 async function load(){try{setError('');const [s,h]=await Promise.all([apiRequest(`/staff/${id}`),apiRequest('/organization/hierarchy')]);setStaff(s);setRegions(Array.isArray(h)?h:[]);const a=(s?.assignments||[]).find((x:any)=>x.active) || s?.assignments?.[0];setRole(a?.role||s?.user?.role||'STAFF');setRegionId(a?.region?.id||s?.region?.id||'');setDivisionId(a?.division?.id||s?.division?.id||'');setAreaId(a?.area?.id||s?.area?.id||'');setBranchId(a?.branch?.id||s?.branch?.id||'')}catch(e:any){setError(e?.message||'Unable to load staff workspace.')}}
 useEffect(()=>{if(id)load()},[id]);
 const region=regions.find(r=>r.id===regionId); const divisions=region?.divisions||[]; const areas=(region?.areas||[]).filter(a=>!divisionId||a.divisionId===divisionId); const branches=(region?.branches||[]).filter(b=>(!divisionId||b.divisionId===divisionId)&&(!areaId||b.areaId===areaId));
 async function assign(){if(!role||!branchId)return setMessage('Select a role and branch before saving the assignment.');setBusy(true);setMessage('');try{await apiRequest(`/staff/${id}/assignments`,{method:'POST',body:JSON.stringify({role,regionId:regionId||undefined,divisionId:divisionId||undefined,areaId:areaId||undefined,branchId,notes:notes||undefined})});setMessage('Role and organizational assignment saved successfully.');setNotes('');await load()}catch(e:any){setMessage(e?.message||'Unable to save assignment.')}finally{setBusy(false)}}
 if(error)return <main><div className="pwfb-alert">{error}</div><Link href="/staff" className="pwfb-secondary-button">← Staff</Link></main>;
 if(!staff)return <main><div className="pwfb-panel">Loading staff workspace…</div></main>;
 const name=[staff.firstName,staff.middleName,staff.lastName].filter(Boolean).join(' ');
 return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">STAFF MANAGEMENT • WORKSPACE</p><h1 className="pwfb-page-title">{name}</h1><p className="pwfb-page-description">{staff.staffId||'Staff record'} • {staff.position||'Staff'} • {staff.branch?.name||'No branch assigned'}</p></div><div className="flex gap-2"><Link href="/staff" className="pwfb-secondary-button">← Staff</Link><Link href="/staff/add" className="pwfb-primary-button">+ Add Staff</Link></div></div>
 <section className="pwfb-stat-grid"><div className="pwfb-stat-card"><span>Current Role</span><strong>{staff.user?.role?.replaceAll('_',' ')||'—'}</strong><small>Login access role</small></div><div className="pwfb-stat-card pwfb-stat-orange"><span>Status</span><strong>{staff.employmentStatus||'ACTIVE'}</strong><small>Employment status</small></div><div className="pwfb-stat-card"><span>Branch</span><strong>{staff.branch?.name||'Unassigned'}</strong><small>{staff.area?.name||'No area'}</small></div><div className="pwfb-stat-card pwfb-stat-orange"><span>Department</span><strong>{staff.department?.name||'—'}</strong><small>{staff.phone||staff.email||'Contact not available'}</small></div></section>
 {message&&<div className="pwfb-alert">{message}</div>}
 <div className="grid gap-5 lg:grid-cols-2"><section className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Role & Branch Assignment</h2><p>Creating a new assignment automatically closes the previous active assignment.</p></div></div><div className="grid gap-4"><label>Role<select value={role} onChange={e=>setRole(e.target.value)} className="h-11 rounded-lg border border-slate-200 px-3">{roles.map(r=><option key={r} value={r}>{r.replaceAll('_',' ')}</option>)}</select></label><label>Region<select value={regionId} onChange={e=>{setRegionId(e.target.value);setDivisionId('');setAreaId('');setBranchId('')}} className="h-11 rounded-lg border border-slate-200 px-3"><option value="">Select Region</option>{regions.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label>Division<select value={divisionId} onChange={e=>{setDivisionId(e.target.value);setAreaId('');setBranchId('')}} disabled={!regionId} className="h-11 rounded-lg border border-slate-200 px-3"><option value="">Select Division</option>{divisions.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Area<select value={areaId} onChange={e=>{setAreaId(e.target.value);setBranchId('')}} disabled={!regionId} className="h-11 rounded-lg border border-slate-200 px-3"><option value="">Select Area</option>{areas.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Branch<select value={branchId} onChange={e=>setBranchId(e.target.value)} disabled={!regionId} className="h-11 rounded-lg border border-slate-200 px-3"><option value="">Select Branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Assignment notes<textarea value={notes} onChange={e=>setNotes(e.target.value)} rows={3} className="rounded-lg border border-slate-200 p-3" placeholder="Optional reason or operational note" /></label><button className="pwfb-primary-button" onClick={assign} disabled={busy}>{busy?'Saving…':'Save New Assignment'}</button></div></section>
 <section className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Assignment History</h2><p>Every role and organizational change is retained.</p></div><span className="pwfb-record-count">{staff.assignments?.length||0} records</span></div><div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>ROLE</th><th>SCOPE</th><th>STARTED</th><th>ENDED</th><th>STATUS</th></tr></thead><tbody>{(staff.assignments||[]).map(a=><tr key={a.id}><td><strong>{a.role.replaceAll('_',' ')}</strong></td><td>{[a.region?.name,a.division?.name,a.area?.name,a.branch?.name].filter(Boolean).join(' → ')||'—'}</td><td>{a.startsAt?new Date(a.startsAt).toLocaleDateString('en-NG'): '—'}</td><td>{a.endsAt?new Date(a.endsAt).toLocaleDateString('en-NG'):'—'}</td><td>{a.active?'ACTIVE':'CLOSED'}</td></tr>)}{!staff.assignments?.length&&<tr><td colSpan={5}>No assignment history found.</td></tr>}</tbody></table></div></section></div>
 </main>;
}
