CREATE TABLE IF NOT EXISTS "RolePermission" (
  "id" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "permission" TEXT NOT NULL,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RolePermission_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "RolePermission_role_permission_key" UNIQUE ("role", "permission")
);

INSERT INTO "RolePermission" ("id","role","permission","enabled") VALUES
('rp_SUPER_ADMIN_WALLET_DEPOSIT','SUPER_ADMIN','WALLET_DEPOSIT',true),
('rp_SUPER_ADMIN_WALLET_WITHDRAWAL','SUPER_ADMIN','WALLET_WITHDRAWAL',true),
('rp_ADMIN_WALLET_DEPOSIT','ADMIN','WALLET_DEPOSIT',true),
('rp_ADMIN_WALLET_WITHDRAWAL','ADMIN','WALLET_WITHDRAWAL',true),
('rp_BRANCH_MANAGER_WALLET_DEPOSIT','BRANCH_MANAGER','WALLET_DEPOSIT',true),
('rp_BRANCH_MANAGER_WALLET_WITHDRAWAL','BRANCH_MANAGER','WALLET_WITHDRAWAL',true),
('rp_TELLER_WALLET_DEPOSIT','TELLER','WALLET_DEPOSIT',true),
('rp_TELLER_WALLET_WITHDRAWAL','TELLER','WALLET_WITHDRAWAL',true),
('rp_STAFF_WALLET_DEPOSIT','STAFF','WALLET_DEPOSIT',true),
('rp_STAFF_WALLET_WITHDRAWAL','STAFF','WALLET_WITHDRAWAL',false),
('rp_CUSTOMER_WALLET_DEPOSIT','CUSTOMER','WALLET_DEPOSIT',true),
('rp_CUSTOMER_WALLET_WITHDRAWAL','CUSTOMER','WALLET_WITHDRAWAL',true)
ON CONFLICT ("role","permission") DO NOTHING;
