plugins {
    id 'com.android.application'
}

android {
    namespace 'com.pwfb.microfinance'
    compileSdk 36

    defaultConfig {
        applicationId 'com.pwfb.microfinance'
        minSdk 23
        targetSdk 36
        versionCode 14
        versionName '1.0.13'
    }
}

dependencies {
    implementation 'androidx.browser:browser:1.9.0'
    implementation 'androidx.webkit:webkit:1.14.0'
    implementation 'androidx.core:core-splashscreen:1.0.1'
}
