"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";

const API = process.env.NEXT_PUBLIC_API_URL || "";
type Branch={id:string;name:string;code?:string;location?:string;status?:string;region?:{name:string};division?:{name:string};area?:{name:string};branchAccounts?:{id:string;accountNumber:string;accountName?:string;provider?:string;status?:string}[];customers?:any[];staff?:any[]};
type Summary={period?:{name?:string;status?:string};staff:{active:number};savings:{total:number};loans:{disbursed:number;count:number};repayments:{total:number;count:number};collections:{total:number;count:number};cashbook:{cashIn:number;cashOut:number;net:number};payroll:{net:number};netCashPosition:number};
const money=(v:any)=>`₦${Number(v||0).toLocaleString("en-NG",{maximumFractionDigits:0})}`;
const operationalRecords=[{label:"Daily Collection",href:"/collections"},{label:"Savings Summary",href:"/savings"},{label:"Loan Summary",href:"/loans"},{label:"Weekly Loan Summary",href:"/loans?view=weekly"},{label:"Bank Transaction",href:"/transactions"},{label:"Cash Book",href:"/cashbook"}];

export default function BranchDetailPage(){
 const {id}=useParams<{id:string}>();const router=useRouter();
 const [branch,setBranch]=useState<Branch|null>(null);const [summary,setSummary]=useState<Summary|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [saving,setSaving]=useState(false);const [name,setName]=useState("");const [location,setLocation]=useState("");
 useEffect(()=>{if(!id)return;Promise.all([fetch(`${API}/branches/${id}`,{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error("Branch not found");return r.json()}),fetch(`${API}/dashboards/branch/${id}`,{credentials:"include"}).then(async r=>{if(!r.ok)throw new Error("Unable to load branch operations");return r.json()})]).then(([b,s])=>{const x=b?.data||b;setBranch(x);setName(x.name||"");setLocation(x.location||"");setSummary(s)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[id]);
 async function save(){setSaving(true);try{const r=await fetch(`${API}/branches/${id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,location})});if(!r.ok)throw new Error("Unable to save branch");const d=await r.json();setBranch(d?.data||d)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 if(loading)return <main className="p-6">Loading branch operations…</main>;
 if(error||!branch)return <main className="p-6 text-red-600">{error||"Branch not found"}</main>;
 const account=branch.branchAccounts?.[0];const branchHref=(href:string)=>`${href}${href.includes("?")?"&":"?"}branchId=${encodeURIComponent(branch.id)}`;
 return <main>
  <div className="pwfb-page-header"><div><p className="pwfb-eyebrow">BRANCH OPERATIONS • {branch.code||branch.id}</p><h1 className="pwfb-page-title">{branch.name}</h1><p className="pwfb-page-description">Live branch workspace using the shared PWFB operational database.</p></div><div className="flex gap-2"><Link href="/staff-dashboard" className="pwfb-primary-button">Staff Dashboard</Link><button className="pwfb-secondary-button" onClick={()=>router.push("/branches")}>← Back</button></div></div>
  <section className="pwfb-panel"><div className="p-6 flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="pwfb-eyebrow">ACTIVE BRANCH</p><h2 className="text-2xl font-black">{branch.name}</h2><p className="text-sm text-slate-500">{branch.code||"No code"} • {branch.location||"Location not set"} • {branch.status||"Active"}</p></div><div className="rounded-xl bg-emerald-50 p-4"><span className="block text-xs text-slate-500">Virtual Account</span><strong>{account?.accountNumber||"Not provisioned"}</strong></div></div></section>
  {summary?.period&&<div className="my-4 rounded-xl bg-slate-50 p-3 text-xs text-slate-600">Financial period: <strong>{summary.period.name}</strong> • {summary.period.status}</div>}
  {summary&&<section className="pwfb-stat-grid"><div className="pwfb-stat-card"><span>Active Staff</span><strong>{summary.staff.active}</strong><small>Assigned to branch</small></div><div className="pwfb-stat-card"><span>Savings</span><strong>{money(summary.savings.total)}</strong><small>Current reporting period</small></div><div className="pwfb-stat-card"><span>Loans Disbursed</span><strong>{money(summary.loans.disbursed)}</strong><small>{summary.loans.count} accounts</small></div><div className="pwfb-stat-card"><span>Repayments</span><strong>{money(summary.repayments.total)}</strong><small>{summary.repayments.count} records</small></div><div className="pwfb-stat-card"><span>Collections</span><strong>{money(summary.collections.total)}</strong><small>{summary.collections.count} records</small></div><div className="pwfb-stat-card"><span>Cash In</span><strong>{money(summary.cashbook.cashIn)}</strong><small>Cashbook receipts</small></div><div className="pwfb-stat-card"><span>Cash Out</span><strong>{money(summary.cashbook.cashOut)}</strong><small>Cashbook payments</small></div><div className="pwfb-stat-card"><span>Net Position</span><strong>{money(summary.netCashPosition)}</strong><small>After payroll impact</small></div></section>}
  <section className="pwfb-panel mt-6"><div className="pwfb-panel-header"><div><h2>Branch Daily Operations</h2><p>Open the real operational modules for this branch.</p></div><span className="pwfb-record-count">6 operations</span></div><div className="grid gap-3 p-6 sm:grid-cols-2 lg:grid-cols-3">{operationalRecords.map(item=><Link key={item.label} href={branchHref(item.href)} className="group rounded-xl border border-emerald-100 bg-emerald-50/60 p-4 transition hover:-translate-y-0.5 hover:border-emerald-300"><strong className="block text-sm text-emerald-900">{item.label}</strong><span className="mt-1 block text-xs text-slate-600">Open {item.label.toLowerCase()} for {branch.name}</span><span className="mt-3 inline-flex text-xs font-bold text-orange-600">Open →</span></Link>)}</div></section>
  <section className="grid gap-6 lg:grid-cols-2 mt-6"><div className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>Cash Reconciliation</h2><p>Live branch cash position.</p></div></div><div className="p-6 space-y-3 text-sm"><div className="flex justify-between"><span>Cash in</span><strong>{money(summary?.cashbook.cashIn)}</strong></div><div className="flex justify-between"><span>Cash out</span><strong>{money(summary?.cashbook.cashOut)}</strong></div><div className="flex justify-between border-t pt-3"><span>Cash net</span><strong>{money(summary?.cashbook.net)}</strong></div><div className="flex justify-between"><span>Payroll</span><strong>{money(summary?.payroll.net)}</strong></div><div className="flex justify-between border-t pt-3 font-black"><span>Net position</span><strong>{money(summary?.netCashPosition)}</strong></div></div></div><div className="pwfb-panel"><div className="pwfb-panel-header"><div><h2>People & History</h2><p>Branch-linked operational records.</p></div></div><div className="flex flex-wrap gap-3 p-6"><Link href="/staff" className="pwfb-secondary-button">Assigned Staff</Link><Link href={branchHref("/customers")} className="pwfb-secondary-button">Customers</Link><Link href={branchHref("/staff-wallet/history")} className="pwfb-secondary-button">Cash History</Link><Link href={branchHref("/reports")} className="pwfb-secondary-button">Branch Reports</Link></div></div></section>
  <section className="pwfb-panel mt-6"><div className="pwfb-panel-header"><div><h2>View / Edit Branch</h2><p>Changes are saved to this database branch.</p></div></div><div className="grid gap-4 p-6 md:grid-cols-2"><label>Branch Name<input className="pwfb-input" value={name} onChange={e=>setName(e.target.value)}/></label><label>Location<input className="pwfb-input" value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Branch ID<input className="pwfb-input" value={branch.id} readOnly/></label><label>Status<input className="pwfb-input" value={branch.status||"ACTIVE"} readOnly/></label></div><div className="px-6 pb-6"><button className="pwfb-primary-button" disabled={saving} onClick={save}>{saving?"Saving…":"Save Branch"}</button></div></section>
 </main>;
}
