"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
const API_URL = process.env.NEXT_PUBLIC_API_URL!;
const types = ["Loan", "Daily Loan", "Weekly Loan", "Individual Loan", "Monthly Loan"];
const INTEREST_RATES = Array.from({ length: 32 }, (_, i) => 5 + i * 0.5);
type Rate = { loanType: string; interestRate: number; active: boolean; updatedAt?: string };
export default function LoanRatesPage() {
  const [rates, setRates] = useState<Rate[]>([]); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  const [createType, setCreateType] = useState(types[0]); const [createRate, setCreateRate] = useState("5");
  async function load() { const res = await fetch(`${API_URL}/loans/rates`, { headers: { Authorization: `Bearer ${localStorage.getItem("token") ?? ""}` } }); const data = await res.json().catch(() => []); setRates(Array.isArray(data) ? data : []); }
  useEffect(() => { load().catch(() => setMessage("Unable to load loan percentages.")); }, []);
  function value(type: string) { return rates.find(r => r.loanType === type)?.interestRate ?? 5; }
  async function save(type: string, rate: number) { setBusy(type); setMessage(""); try { const res = await fetch(`${API_URL}/loans/rates/${encodeURIComponent(type)}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") ?? ""}` }, body: JSON.stringify({ interestRate: rate }) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.message || "Could not save interest percentage"); setMessage(`${type} interest percentage saved.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save interest percentage"); } finally { setBusy(""); } }
  async function createInterest() { const rate = Number(createRate); if (!INTEREST_RATES.includes(rate)) { setMessage("Select an interest percentage from 5% to 20.5%."); return; } await save(createType, rate); }
  return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">SUPER ADMINISTRATION</p><h1 className="pwfb-page-title">Loan Interest Control</h1><p className="pwfb-page-description">Super Admin can create and change the interest percentage used for each loan type.</p></div><Link href="/loans/add" className="pwfb-primary-button">Create Loan</Link></div>{message && <div className="pwfb-panel" style={{ marginBottom: 16 }}><strong>{message}</strong></div>}
  <section className="pwfb-panel" style={{ maxWidth: 900, marginBottom: 20 }}><div className="pwfb-panel-header"><div><h2>Create Interest</h2><p>Set the active interest percentage for a loan type. Available rates are 5% to 20.5% in 0.5% steps.</p></div></div><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit,minmax(180px,1fr))", gap: 12, alignItems: "end" }}><label><strong>Loan Type</strong><select value={createType} onChange={e => setCreateType(e.target.value)} style={{ width: "100%", marginTop: 6, padding: 10 }}>{types.map(type => <option key={type}>{type}</option>)}</select></label><label><strong>Interest Percentage</strong><select value={createRate} onChange={e => setCreateRate(e.target.value)} style={{ width: "100%", marginTop: 6, padding: 10 }}>{INTEREST_RATES.map(rate => <option key={rate} value={rate}>{rate.toFixed(1).replace(".0", "")} %</option>)}</select></label><button className="pwfb-primary-button" disabled={busy === createType} onClick={createInterest}>{busy === createType ? "Saving…" : "Create Interest"}</button></div></section>
  <section className="pwfb-panel" style={{ maxWidth: 900 }}><div className="pwfb-panel-header"><div><h2>Loan Type Interest Rates</h2><p>Existing loans keep their captured percentage; changing a rate affects new loans using that loan type.</p></div></div><div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Loan Type</th><th>Interest %</th><th>Interest on ₦100,000</th><th>Action</th></tr></thead><tbody>{types.map(type => <RateRow key={type} type={type} rate={value(type)} busy={busy === type} onSave={save} />)}</tbody></table></div></section></main>;
}
function RateRow({ type, rate, busy, onSave }: { type: string; rate: number; busy: boolean; onSave: (type: string, rate: number) => Promise<void> }) { const [input, setInput] = useState(String(rate)); useEffect(() => setInput(String(rate)), [rate]); const example = 100000 * Number(input || 0) / 100; return <tr><td><strong>{type}</strong></td><td><select value={input} onChange={e => setInput(e.target.value)} style={{ width: 150 }} aria-label={`${type} interest percentage`}>{INTEREST_RATES.map(rateOption => <option key={rateOption} value={rateOption}>{rateOption.toFixed(1).replace(".0", "")} %</option>)}</select></td><td>₦{example.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td><td><button className="pwfb-primary-button" disabled={busy} onClick={() => onSave(type, Number(input))}>{busy ? "Saving…" : "Save"}</button></td></tr>; }
