"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
const API_URL = process.env.NEXT_PUBLIC_API_URL!;
const types = ["Loan", "Daily Loan", "Weekly Loan", "Individual Loan", "Monthly Loan"];
type Rate = { loanType: string; interestRate: number; active: boolean; updatedAt?: string };
export default function LoanRatesPage() {
  const [rates, setRates] = useState<Rate[]>([]); const [busy, setBusy] = useState(""); const [message, setMessage] = useState("");
  async function load() { const res = await fetch(`${API_URL}/loans/rates`, { headers: { Authorization: `Bearer ${localStorage.getItem("token") ?? ""}` } }); const data = await res.json().catch(() => []); setRates(Array.isArray(data) ? data : []); }
  useEffect(() => { load().catch(() => setMessage("Unable to load loan percentages.")); }, []);
  function value(type: string) { return rates.find(r => r.loanType === type)?.interestRate ?? 0; }
  async function save(type: string, rate: number) { setBusy(type); setMessage(""); try { const res = await fetch(`${API_URL}/loans/rates/${encodeURIComponent(type)}`, { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("token") ?? ""}` }, body: JSON.stringify({ interestRate: rate }) }); const data = await res.json().catch(() => ({})); if (!res.ok) throw new Error(data.message || "Could not save rate"); setMessage(`${type} percentage saved.`); await load(); } catch (e) { setMessage(e instanceof Error ? e.message : "Could not save rate"); } finally { setBusy(""); } }
  return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">ADMINISTRATION</p><h1 className="pwfb-page-title">Loan Percentages</h1><p className="pwfb-page-description">Set the interest percentage used automatically when each loan type is registered.</p></div><Link href="/loans/add" className="pwfb-primary-button">Create Loan</Link></div>{message && <div className="pwfb-panel" style={{ marginBottom: 16 }}><strong>{message}</strong></div>}<section className="pwfb-panel" style={{ maxWidth: 900 }}><div className="pwfb-panel-header"><div><h2>Loan Type Rates</h2><p>Existing loans keep the percentage captured when they were created.</p></div></div><div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Loan Type</th><th>Interest %</th><th>Interest on ₦100,000</th><th>Action</th></tr></thead><tbody>{types.map(type => <RateRow key={type} type={type} rate={value(type)} busy={busy === type} onSave={save} />)}</tbody></table></div></section></main>;
}
function RateRow({ type, rate, busy, onSave }: { type: string; rate: number; busy: boolean; onSave: (type: string, rate: number) => Promise<void> }) { const [input, setInput] = useState(String(rate)); useEffect(() => setInput(String(rate)), [rate]); const example = 100000 * Number(input || 0) / 100; return <tr><td><strong>{type}</strong></td><td><input type="number" min="0" step="0.01" value={input} onChange={e => setInput(e.target.value)} style={{ width: 130 }} /> %</td><td>₦{example.toLocaleString("en-NG", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}</td><td><button className="pwfb-primary-button" disabled={busy} onClick={() => onSave(type, Number(input))}>{busy ? "Saving…" : "Save"}</button></td></tr>; }
