"use client";

import { useEffect, useMemo, useState } from "react";
import { pwfbApi } from "../../lib/pwfb-api";

type Customer={id:string;firstName?:string;lastName?:string;name?:string};
type Wallet={balance:number;currency?:string};
type BankingTransaction={id:string;type?:string;amount:number;description?:string;status?:string;createdAt?:string;created_at?:string};
type Bank={id?:string;code:string;name:string;shortName?:string};
type Operation="deposit"|"withdraw"|"transfer"|"bank-transfer";

export default function BankingPage(){
 const [customers,setCustomers]=useState<Customer[]>([]),[customerId,setCustomerId]=useState(""),[wallet,setWallet]=useState<Wallet|null>(null),[transactions,setTransactions]=useState<BankingTransaction[]>([]);
 const [banks,setBanks]=useState<Bank[]>([]),[bankCode,setBankCode]=useState(""),[bankSearch,setBankSearch]=useState(""),[accountNumber,setAccountNumber]=useState(""),[accountName,setAccountName]=useState(""),[operation,setOperation]=useState<Operation>("deposit");
 const [amount,setAmount]=useState(""),[description,setDescription]=useState(""),[reference,setReference]=useState(""),[recipientId,setRecipientId]=useState(""),[loading,setLoading]=useState(false),[verifying,setVerifying]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);const o=p.get("operation");if(["deposit","withdraw","transfer","bank-transfer"].includes(o||""))setOperation(o as Operation);pwfbApi.customers.search().then(d=>setCustomers(Array.isArray(d)?d:d?.data??[])).catch(()=>setCustomers([]));pwfbApi.banking.institutions().then(d=>{const list=Array.isArray(d)?d:d?.data??[];setBanks(list.map((b:any)=>({id:b.id,code:String(b.code??b.bankCode??""),name:String(b.name??b.bankName??b.institutionName??""),shortName:b.shortName})).filter((b:Bank)=>b.code&&b.name));}).catch(e=>{console.error("Bank institution load failed",e);setBanks([]);});},[]);
 useEffect(()=>{if(!customerId){setWallet(null);setTransactions([]);return;}Promise.all([pwfbApi.banking.customerWallet(customerId),pwfbApi.banking.customerTransactions(customerId)]).then(([w,t])=>{setWallet(w);setTransactions(Array.isArray(t)?t:t?.data??[])}).catch(()=>{setWallet(null);setTransactions([])});},[customerId]);
 useEffect(()=>{if(!bankCode||!/^\d{10}$/.test(accountNumber))return;let cancelled=false;setVerifying(true);setAccountName("");pwfbApi.banking.accountName(bankCode,accountNumber).then((r:any)=>{if(!cancelled)setAccountName(String(r?.accountName??r?.data?.accountName??""))}).catch(()=>{if(!cancelled)setAccountName("")}).finally(()=>{if(!cancelled)setVerifying(false)});return()=>{cancelled=true}},[bankCode,accountNumber]);
 const filteredBanks=useMemo(()=>{const q=bankSearch.trim().toLowerCase();if(!q)return banks;return banks.filter(b=>`${b.name} ${b.shortName||""} ${b.code}`.toLowerCase().includes(q));},[banks,bankSearch]);
 const selectedCustomer=customers.find(c=>c.id===customerId);const customerName=(c:Customer)=>c.name||[c.firstName,c.lastName].filter(Boolean).join(" ")||c.id;
 function chooseOperation(o:Operation){setOperation(o);setMessage("");setRecipientId("");const u=new URL(window.location.href);u.searchParams.set("operation",o);window.history.replaceState({},"",u.toString())}
 async function performOperation(){if(!customerId)return setMessage("Select a customer first.");const n=Number(amount);if(!Number.isFinite(n)||n<=0)return setMessage("Enter a valid amount greater than zero.");if(!reference.trim())return setMessage("Enter a transaction reference.");if(operation!=="transfer"&&(!bankCode||!accountNumber||!/^\d{10}$/.test(accountNumber)))return setMessage("Select a bank and enter a valid 10-digit account number.");if((operation==="withdraw"||operation==="bank-transfer")&&!accountName)return setMessage("Verify the bank account name before continuing.");if(operation==="withdraw"&&wallet&&n>Number(wallet.balance||0))return setMessage("Insufficient wallet balance for this withdrawal.");if(operation==="transfer"&&!recipientId)return setMessage("Select a transfer recipient.");setLoading(true);setMessage("");try{const common={amount:n,description,reference:reference.trim()};if(operation==="deposit")await pwfbApi.banking.deposit(customerId,{...common,bankCode,accountNumber,accountName});else if(operation==="withdraw")await pwfbApi.banking.withdraw(customerId,{...common,bankCode,accountNumber,accountName});else if(operation==="bank-transfer")await pwfbApi.banking.bankTransfer(customerId,{amount:n,description,bankCode,accountNumber,accountName});else await pwfbApi.banking.transfer(customerId,{recipientCustomerId:recipientId,...common});const [w,t]=await Promise.all([pwfbApi.banking.customerWallet(customerId),pwfbApi.banking.customerTransactions(customerId)]);setWallet(w);setTransactions(Array.isArray(t)?t:t?.data??[]);setAmount("");setDescription("");setReference("");setRecipientId("");setAccountNumber("");setAccountName("");setMessage("Operation completed successfully")}catch(e){setMessage(e instanceof Error?e.message:"Operation could not be completed.")}finally{setLoading(false)}}
 const title={deposit:"Deposit Funds",withdraw:"Withdraw Funds",transfer:"Customer Transfer","bank-transfer":"Bank Transfer"}[operation];
 return <main className="pwfb-banking-page"><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">FINANCE OPERATIONS</p><h1 className="pwfb-page-title">Banking Operations</h1><p className="pwfb-page-description">Manage customer deposits, withdrawals and transfers across Nigerian banks.</p></div></div>
 <section className="pwfb-panel pwfb-banking-customer-panel"><div className="pwfb-panel-header"><div><h2>Customer Wallet</h2><p>Select a customer to manage banking activity.</p></div></div><div className="pwfb-banking-panel-body"><label className="pwfb-label">Customer</label><select value={customerId} onChange={e=>setCustomerId(e.target.value)} className="pwfb-input"><option value="">Select customer</option>{customers.map(c=><option key={c.id} value={c.id}>{customerName(c)}</option>)}</select>{selectedCustomer&&wallet&&<div className="pwfb-banking-balance"><div><span>AVAILABLE BALANCE</span><strong>{wallet.currency||"NGN"} {Number(wallet.balance||0).toLocaleString()}</strong><small>{customerName(selectedCustomer)}</small></div></div>}</div></section>
 <section className="pwfb-panel pwfb-banking-operation-panel"><div className="pwfb-panel-header"><div><h2>Transaction Operation</h2><p>Choose an operation. External bank operations support bank selection and account verification.</p></div></div><div className="pwfb-banking-panel-body"><div className="pwfb-banking-operation-grid">{(["deposit","withdraw","transfer","bank-transfer"] as Operation[]).map(o=><button key={o} type="button" className={`pwfb-banking-operation ${operation===o?"pwfb-banking-operation-active":""}`} onClick={()=>chooseOperation(o)}><span>{o==="deposit"?"💰":o==="withdraw"?"💵":o==="transfer"?"↔️":"🏦"}</span><strong>{o==="bank-transfer"?"Bank Transfer":o.charAt(0).toUpperCase()+o.slice(1)}</strong><small>{o==="deposit"?"Add money to customer wallet":o==="withdraw"?"Withdraw to a bank account":o==="transfer"?"Move money to another PWFB customer":"Send money to any supported bank"}</small></button>)}</div></div></section>
 <section className="pwfb-panel pwfb-banking-form-panel"><div className="pwfb-panel-header"><div><h2>{title}</h2><p>Search and select the destination bank below.</p></div></div><div className="pwfb-banking-panel-body"><div className="pwfb-banking-form">
 {(operation!=="transfer")&&<><div><label className="pwfb-label">Bank</label><input className="pwfb-input" type="search" value={bankSearch} onChange={e=>setBankSearch(e.target.value)} placeholder="Search bank by name or code" autoComplete="off"/><select className="pwfb-input" value={bankCode} onChange={e=>{setBankCode(e.target.value);setAccountName("")}} size={Math.min(Math.max(filteredBanks.length,1),8)} style={{marginTop:8}}><option value="">Select bank</option>{filteredBanks.map(b=><option key={`${b.code}-${b.name}`} value={b.code}>{b.name}{b.shortName?` (${b.shortName})`:""}</option>)}</select><small>{filteredBanks.length} bank{filteredBanks.length===1?"":"s"} found{bankSearch.trim()?` for “${bankSearch.trim()}”`:""}.</small>{banks.length===0&&<small>Unable to load bank list. Check banking provider configuration.</small>}</div><div><label className="pwfb-label">Account Number</label><input className="pwfb-input" inputMode="numeric" maxLength={10} value={accountNumber} onChange={e=>setAccountNumber(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="10-digit account number"/></div>{(operation==="withdraw"||operation==="bank-transfer")&&<div><label className="pwfb-label">Verified Account Name</label><input className="pwfb-input" value={verifying?"Verifying account...":accountName} readOnly placeholder="Select bank and enter account number"/></div>}</>}
 {operation==="transfer"&&<div><label className="pwfb-label">Transfer Recipient</label><select className="pwfb-input" value={recipientId} onChange={e=>setRecipientId(e.target.value)}><option value="">Select PWFB customer</option>{customers.filter(c=>c.id!==customerId).map(c=><option key={c.id} value={c.id}>{customerName(c)}</option>)}</select></div>}
 <div><label className="pwfb-label">Amount</label><input className="pwfb-input" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Enter amount"/></div><div><label className="pwfb-label">Description / Narration</label><input className="pwfb-input" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Transaction description"/></div><div><label className="pwfb-label">Transaction Reference</label><input className="pwfb-input" value={reference} onChange={e=>setReference(e.target.value)} placeholder="e.g. PWFB-BANK-001"/></div></div><button type="button" className="pwfb-primary-button pwfb-banking-submit" disabled={loading} onClick={performOperation}>{loading?"Processing...":title}</button>{message&&<div className="pwfb-alert pwfb-banking-message">{message}</div>}</div></section>
 <section className="pwfb-panel pwfb-banking-transactions-panel"><div className="pwfb-panel-header"><div><h2>Recent Transactions</h2><p>Latest banking activity for the selected customer.</p></div><span className="pwfb-record-count">{transactions.length} transactions</span></div>{!customerId?<div className="pwfb-banking-empty">Select a customer to view transaction history.</div>:transactions.length===0?<div className="pwfb-banking-empty">No banking transactions found for this customer.</div>:<div className="pwfb-table-wrap"><table className="pwfb-table"><thead><tr><th>Type</th><th>Amount</th><th>Description</th><th>Status</th><th>Date</th></tr></thead><tbody>{transactions.map(t=><tr key={t.id}><td>{t.type||"TRANSACTION"}</td><td>₦{Number(t.amount||0).toLocaleString()}</td><td>{t.description||"—"}</td><td>{t.status||"COMPLETED"}</td><td>{t.createdAt||t.created_at?new Date(t.createdAt||t.created_at!).toLocaleString():"—"}</td></tr>)}</tbody></table></div>}</section></main>;
}
