"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
const API_URL = process.env.NEXT_PUBLIC_API_URL!;
const TYPES = ["Loan", "Daily Loan", "Weekly Loan", "Individual Loan", "Monthly Loan"];
type Rate = { loanType: string; interestRate: number };
type Form = { customerId:string; firstName:string; middleName:string; lastName:string; phone:string; email:string; address:string; dateOfBirth:string; loanType:string; amount:string; duration:string; repaymentFrequency:string; purpose:string; passportPhoto:string; guarantorId:string };
const initial: Form = { customerId:"",firstName:"",middleName:"",lastName:"",phone:"",email:"",address:"",dateOfBirth:"",loanType:"Loan",amount:"",duration:"",repaymentFrequency:"Weekly",purpose:"",passportPhoto:"",guarantorId:"" };
export default function AddLoanPage(){
 const router=useRouter(); const [form,setForm]=useState(initial); const [rates,setRates]=useState<Rate[]>([]); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false);
 const set=(name:keyof Form,value:string)=>setForm(o=>({...o,[name]:value}));
 useEffect(()=>{fetch(`${API_URL}/loans/rates`,{headers:{Authorization:`Bearer ${localStorage.getItem("token")??""}`}}).then(r=>r.json()).then(d=>setRates(Array.isArray(d)?d:[])).catch(()=>{});},[]);
 const rate=Number(rates.find(r=>r.loanType===form.loanType)?.interestRate??0); const amount=Number(form.amount||0); const duration=Math.max(1,Number(form.duration||1)); const interest=useMemo(()=>amount*rate/100,[amount,rate]); const total=amount+interest; const installment=total/duration;
 const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});
 async function passport(file?:File){if(!file)return;try{set("passportPhoto",await fileToDataUrl(file));}catch{setMessage("Could not read passport photo.");}}
 async function submit(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("Creating loan registration...");try{const res=await fetch(`${API_URL}/loans`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${localStorage.getItem("token")??""}`},body:JSON.stringify({customerId:form.customerId,amount,loanType:form.loanType,duration,repaymentFrequency:form.repaymentFrequency,purpose:form.purpose,passportPhoto:form.passportPhoto,status:"PENDING"})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.message||"Unable to create loan.");const id=data.id??data.loan?.id;setMessage("Loan created. Opening guarantor registration...");setTimeout(()=>id?router.push(`/loans/guarantor/add?loanId=${encodeURIComponent(id)}`):router.push("/loans"),400);}catch(e){setMessage(e instanceof Error?e.message:"Unable to create loan.");}finally{setSaving(false);}}
 return <main><div className="pwfb-page-header"><div><p className="pwfb-eyebrow">PWFB LOANS</p><h1 className="pwfb-page-title">Add Loan</h1><p className="pwfb-page-description">Register the borrower, capture a passport photograph and complete guarantor registration.</p></div><Link href="/admin/loan-rates" className="pwfb-secondary-button">Manage Percentages</Link></div>
 <section className="pwfb-panel" style={{maxWidth:1050}}><div className="pwfb-panel-header"><div><h2>Loan Registration Form</h2><p>The interest percentage is automatically taken from the Admin loan-type settings.</p></div></div>
 <form onSubmit={submit} style={{display:"grid",gap:16}}><h3>Customer information</h3><div style={{display:"grid",gridTemplateColumns:"repeat(4,minmax(0,1fr))",gap:12}}>{[["customerId","Customer ID"],["firstName","First name"],["middleName","Middle name"],["lastName","Last name"]].map(([n,p])=><input key={n} className="w-full border p-3 rounded" placeholder={p} value={form[n as keyof Form]} onChange={e=>set(n as keyof Form,e.target.value)} required={n!=="middleName"}/>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12}}><input className="w-full border p-3 rounded" placeholder="Phone number" value={form.phone} onChange={e=>set("phone",e.target.value)} required/><input className="w-full border p-3 rounded" type="email" placeholder="Email" value={form.email} onChange={e=>set("email",e.target.value)}/><input className="w-full border p-3 rounded" type="date" value={form.dateOfBirth} onChange={e=>set("dateOfBirth",e.target.value)}/></div><input className="w-full border p-3 rounded" placeholder="Residential address" value={form.address} onChange={e=>set("address",e.target.value)}/>
 <label className="border rounded p-4"><strong>Passport photograph</strong><p style={{margin:"4px 0 8px"}}>Take a passport snap with the phone camera or upload an existing photo.</p><input type="file" accept="image/*" capture="user" onChange={e=>passport(e.target.files?.[0])}/>{form.passportPhoto&&<p>✓ Passport photo captured</p>}</label>
 <h3>Loan details</h3><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:12}}><select className="w-full border p-3 rounded" value={form.loanType} onChange={e=>set("loanType",e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select><input className="w-full border p-3 rounded" type="number" min="1" placeholder="Loan amount (₦)" value={form.amount} onChange={e=>set("amount",e.target.value)} required/><input className="w-full border p-3 rounded" type="number" min="1" placeholder="Number of installments" value={form.duration} onChange={e=>set("duration",e.target.value)} required/><select className="w-full border p-3 rounded" value={form.repaymentFrequency} onChange={e=>set("repaymentFrequency",e.target.value)}><option>Daily</option><option>Weekly</option><option>Monthly</option></select><input className="w-full border p-3 rounded" placeholder="Loan purpose" value={form.purpose} onChange={e=>set("purpose",e.target.value)} required/><div className="border rounded p-3"><strong>Admin interest</strong><div style={{fontSize:24,fontWeight:800}}>{rate.toFixed(2)}%</div></div></div>
 <div className="pwfb-stat-grid"><div className="pwfb-stat-card"><span>Principal</span><strong>₦{amount.toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></div><div className="pwfb-stat-card"><span>Interest</span><strong>₦{interest.toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></div><div className="pwfb-stat-card pwfb-stat-orange"><span>Total repayment</span><strong>₦{total.toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></div><div className="pwfb-stat-card"><span>Installment</span><strong>₦{installment.toLocaleString("en-NG",{minimumFractionDigits:2})}</strong></div></div>
 <div className="rounded border p-4" style={{background:"#fff7ed"}}><strong>Guarantor registration</strong><p style={{margin:"5px 0"}}>After the loan is saved, the full guarantor form opens automatically. It supports guarantor identity, passport and ID document.</p><input className="w-full border p-3 rounded" placeholder="Existing guarantor ID (optional)" value={form.guarantorId} onChange={e=>set("guarantorId",e.target.value)}/></div>
 <div style={{display:"flex",gap:10}}><button className="pwfb-primary-button" type="submit" disabled={saving}>{saving?"Creating…":"Create Loan + Register Guarantor"}</button><button type="button" className="border rounded px-4 py-2" onClick={()=>router.push("/loans")}>Cancel</button></div>{message&&<p>{message}</p>}</form></section></main>;
}
